Remove pending db
zcash/ZcashLightClientKit pull request #1001
Opened 2023-04-20 22:23 UTC by pacu

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-05-04 09:55 UTC, Chlup requested changes

2023-05-04 09:55 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "1.14.0"
Is the downgrade of these package intentional or is it Xcode magic?

2023-05-04 09:55 UTC, Chlup commented on Sources/ZcashLightClientKit/Providers/ResourceProvider.swift
> +//    public var cacheDbURL: URL {
Forgotten commented code.

2023-05-04 09:55 UTC, Chlup commented on Sources/ZcashLightClientKit/Extensions/ZcashTransaction+Pending.swift
> +public extension ZcashTransaction.Overview {
Do we need extension and another file for this? Can't we put this method right into `TransactionEntity.swift` file? It will be easy to discover this method when reading code.

2023-05-04 09:55 UTC, Chlup commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +
Two empty lines means linter warning. :)

2023-05-04 09:55 UTC, Chlup commented on Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
> +//                    XCTAssertEqual(value.recipient, self.data.pendingTransactionEntity.recipient)
Is this comment intentional?

2023-05-04 09:55 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    // sourcery: mockedName="getTransactionOutputsForTransaction"
I love that you found that there is option for changing mocked name. :)

2023-05-04 11:41 UTC, pacu commented on Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "1.14.0"
Xcode magic 🪄 🫠

2023-05-05 07:33 UTC, Chlup requested changes

2023-05-05 07:33 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/NotesDao.swift
> -            throw ZcashError.notesDAOReceivedCount(error)
Please also remove these errors.

2023-05-05 07:33 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> -                throw ZcashError.pendingTransactionDecodeInvalidData(["toAddress", "toInternalAccount"])
Please also remove errors that are used in this file

2023-05-05 15:05 UTC, Chlup approved these changes

2023-05-05 17:30 UTC, merged