[#442] Implement parallel downloading and scanning
zcash/ZcashLightClientKit pull request #1009
Opened 2023-04-27 13:25 UTC by Chlup

- `BlockDownloaderImpl` is changed. It now spawns detached Task to
  download blocks. So blocks can be downloaded in parallel with scanning
  process.
- `Synchronizer.stop()` is no longer async.
- Blocks cache cleaning is changed. It's not possible to drop the whole
  cache now. There are some blocks pre-downloaded which weren't scanned
  yet.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-05-01 21:13 UTC, pacu requested changes

2023-05-01 21:13 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
I've detected a geometrical memory usage increase. Object graph points out to this section of the code. 
![image](https://user-images.githubusercontent.com/484008/235532281-e933257d-d375-4172-a46c-98d9e1858a59.png)
![image](https://user-images.githubusercontent.com/484008/235532311-4af3dbfe-20aa-41cd-8031-c1132e0a1b68.png)
![image](https://user-images.githubusercontent.com/484008/235532317-a58acd7b-79f9-46c1-9be8-e22ffae69c0e.png)

![image](https://user-images.githubusercontent.com/484008/235532328-2b80abec-c218-45a7-b235-a94f9766dac8.png)
![image](https://user-images.githubusercontent.com/484008/235532381-ced91038-f495-4858-9cce-5f03cdb67ba8.png)

2023-05-02 06:32 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = RLPRR8CPQG;
I did it intentionally. Unknown team was set there so I changed it to ECC team to be able to run sample app on a real device.

2023-05-05 07:39 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +                await blockDownloader.setDownloadLimit(processingRange.upperBound + (2 * batchSize))
There is no deep idea behind this. I just wanted to setup some reasonable buffer for downloading. I added a comment.

2023-05-05 07:42 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift
> +    ) async throws -> BlockHeight {
It could be done somehow. But It means to do changes in `BlockScanner` and change how it is used. It is not super big change but it is not trivial change. And it will increase scope of this ticket. If we want to play with this we can do it in future.

2023-05-05 07:46 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
This is not cause by this PR. And as I wrote in #1016 it looks like this isn't problem for any real user.

2023-05-05 12:45 UTC, pacu approved these changes

2023-05-05 15:06 UTC, merged