[#700] CompactBlockProcessor as state machine proof of concept
zcash/ZcashLightClientKit pull request #1024
Opened 2023-05-05 15:17 UTC by Chlup

- For now I created `CompactBlockProcessorNG` where I started with implementation of the state machine. I did it to not break the rest of the SDK. This change will be merged to the feature branch. And before it is merged to `main` branch code from `CompactBlockProcessorNG` will be moved to `CompactBlockProcessor`.
- The new code is not used. It just shows and explains how it is done. It is proof of concept.
- I did put either commented current code or comment to some places to explain what should be done there.
- New important data types:
  - `ActionContext` is context that can hold any data that needs to be shared between actions. For example sync ranges or current state.
  - `CBPState` is state of the `CompactBlockProcessor`. Each state is handled by one action. This doesn't apply to terminal states like `finished` or `failed`.
  - `ActionProgress` is very similar to `CompactBlockProgress`. Different actions reports progress differently and `ActionProgress` represents this.
  - `Action` is protocol that defines API of an action. It has one run method that executes the code of the action
- CBP first creates actions for (almost) each state in `makeActions()` method. Then the "magic" is done in `CompactBlockProcessorNG.run()` method. Here is main loop which takes action for current state and execute it. It's expected that action does it's work and then updates the context with new state. And this happens until some terminal state (`finished`, `failed`, `stopped`) is reached.
- After the transition to state machine API of the `CompactBlockProcessor` should stay the same. No changes should be required in `SDKSynchronizer`.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-05-05 19:17 UTC, pacu commented
Great draft!
I like the way things are broken down in a more chewable and extensible way.

I have some question around the run() part of things.

How can actions be orchestrated in concurrently?

We currently do scanning and download at the same time. For DAGsync I imagine there would be other tasks that will need to be done in parallel as well such as downloading blocks, downloading found transactions, decrypting downloaded transactions and scanning blocks altogether.

2023-05-05 20:02 UTC, pacu requested changes
reviewed. left comments.

2023-05-07 18:04 UTC, Chlup commented
> Great draft! I like the way things are broken down in a more chewable and extensible way.
> 
> I have some question around the run() part of things.
> 
> How can actions be orchestrated in concurrently?
> 
> We currently do scanning and download at the same time. For DAGsync I imagine there would be other tasks that will need to be done in parallel as well such as downloading blocks, downloading found transactions, decrypting downloaded transactions and scanning blocks altogether.

@pacu Only one action can run at one time. Parallel will work with state machine in same as it works now. For example download action runs. It uses `BlockDownloaderImpl` to download blocks. And `BlockDownloaderImpl` spawns it's own task  to do downloading while other actions run. And if some action need specific data async waiting can be used (same as in `BlockDownloderImpl.waitUntilRequestedBlocksAreDownloaded`) or some waiting pull mechanism can be built. 

Or we can have multiple state machines that works in paralel. `CompactBlockProcessor` will own multiple state machines. Each machine can run on it's own. And `CompactBlockProcessor` just syncs outputs from separate machines. I didn't used this approach now. But in principle it's the same.

2023-05-09 10:49 UTC, pacu approved these changes

2023-05-09 10:51 UTC, merged