[#700] Make CBP state machine work
zcash/ZcashLightClientKit pull request #1092
Opened 2023-05-15 12:45 UTC by Chlup

- Rebase feature branch on `main` and port all the changes from `main` to state machine (for example how enhance is called changed).
- Moves all the code from `CompactBlockProcessorNG` to `CompactBlockProcessor`. Deleted `CompactBlockProcessorNG.swift` file. Thanks to this we don't loose changes history in `CompactBlockProcessor.swift`.
- Do necessary changes to make it work. Just few tweaks.
- Sync process works. Tests are not even compilable. But this will be fixed in next PRs. This one is big enough.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-05-15 17:20 UTC, pacu requested changes

2023-05-15 17:20 UTC, pacu commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        while true {
I believe this is a risk. we probably want a variable that let us stop the processor forcefully at request to break this infinite loop.

2023-05-16 12:12 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        while true {
I am not sure if new variable is necessary. Now the loop is controlled by the code inside the loop. And if it decides the loop shouldn't continue it breaks the loop. It is same as setting variable to `false`. Forget to add right `break` is same as forget to set variable to `false`. I don't see any additional security. 

The variable brings more complexity because it is new state. Can you please describe any specific case when this variable could help?

I can swift from break to this variable if you want. I just don't see reason why.

2023-05-16 18:30 UTC, pacu commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        while true {
I hadn't seen the parent task initiated calling run(). I think that should make `stop()` fail-proof and avoid any possible infinite loops of the run loop. 

I wonder if we want the `run()` loop to have any sleeps when idle.

2023-05-17 06:55 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        while true {
When CBP is idle and no actions are handled then loop is interrupted and `run()` finishes. It runs only when sync process is in progress.

2023-05-17 07:24 UTC, merged