[#1111] Change storage for InternalSyncProgress
zcash/ZcashLightClientKit pull request #1114
Opened 2023-05-22 07:46 UTC by Chlup

Closes #1111

- `InternalSyncProgress` has now new disk storage implementation: `InternalSyncProgressDiskStorage`.
- When then `UserDefaults` was used as disk storage there were no IO errors to handle. But now the code in `InternalSyncProgressDiskStorage` writes to files and reads from files. So there are errors to handle. Because of this protocol `InternalSyncProgressStorage` changed a bit and API of `InternalSyncProgress` changed a bit. Now all the functions throws.
- It is possible to make progress storage IO errors silent but I think that storing of the progress is very essential to the sync process. So I think that when progress storage fails then the sync process should fail.
- `Initializer` has new parameter `generalStorageURL`. It is directory where `InternalSyncProgressDiskStorage` stores progress files. In future this can be used for storing any data the SDK wants.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-05-22 23:33 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgressDiskStorage.swift
> +                resourceValues.isExcludedFromBackup = true
This makes me think if we should also exclude from backup the dataDb and fsBlockRootDir.

2023-05-22 23:54 UTC, pacu requested changes
I have a couple of questions or ideas about how we could give this a small twist

2023-05-22 23:54 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +        let latestDownloadedBlockHeight = try await self.latestDownloadedBlockHeight
This could be "cheating" because is implementation led but we could use `async let` and fetch these values in parallel. If the backend storage would fetch it serially there won't be a difference. Am I getting it straight?

2023-05-22 23:54 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +        let generalStorageURL: URL
What could we do to not having to expose this backend implementation?

2023-05-23 05:47 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgressDiskStorage.swift
> +                resourceValues.isExcludedFromBackup = true
I will create ticket for that.

2023-05-23 05:47 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +        let latestDownloadedBlockHeight = try await self.latestDownloadedBlockHeight
I am sorry I don't understand what you mean.

2023-05-23 05:49 UTC, Chlup commented on Sources/ZcashLightClientKit/Initializer.swift
> +        let generalStorageURL: URL
The SDK could find path to documents on it's own. But the SDK could find paths for all other storages (blocks, dataDB...). I guess there is some reason why the client app can pass these paths. So I did this in same manner. 

Or we can change this in different way. The client app can pass single URL of one directory. And the SDK stores everything in that directory. But this is bigger change. It is out of scope of this ticket.

2023-05-23 05:52 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgressDiskStorage.swift
> +                resourceValues.isExcludedFromBackup = true
#1119

2023-05-23 11:45 UTC, pacu approved these changes

2023-05-23 16:43 UTC, merged