M1 fixes (#309)
zcash/ZcashLightClientKit pull request #316
Opened 2021-10-01 02:18 UTC by dh-ecc

[Addressing #309]

This is the absolute bare minimum diff to get the pod integration working for M1 machines, which can be demonstrated in this repo by `pod install`ing in the `Example/ZcashLightClientSample/` directory and running on simulator.

In doing so we remove some rust build dependencies, but (at the time of writing) can only build on the `rust nightly` toolchain, so we add this as a dependency.

**Caveats / Known issues**
- This works _only_ for cocoapods integration, other modes of building have not been updated.
- We currently only build the rust library for a _single_ architecture at a time, so this prevents some types of archive builds. (This is addressed with xcframeworks in the assessment of #311)
- The docs have not been updated since they will likely be superceded to remove rust dependency a consumer (and to some extent a contributor) of the SDK.
- The `Cargo.lock` updates are sufficient to make the rust lib build correctly on the nightly toolchain, however I don't know if this is the most idiomatic way to declare this, I feel like there could be a better alternative by declaring something in the `Cargo.toml` instead.

The following  commands should be sufficient to test this working and should work on _both_ intel and m1 macs.
It assumes you have working `rustup` and `pod` commands, try running it in a `/tmp/` folder 😄 

```sh
rustup toolchain add nightly
rustup +nightly target add \
x86_64-apple-ios \
aarch64-apple-ios \
aarch64-apple-ios-sim
git clone git@github.com:dh-ecc/ZcashLightClientKit.git
cd ZcashLightClientKit
git checkout m1-fixes
cd Example/ZcashLightClientSample
pod install
SIMULATOR_ID="$(xcrun simctl list devices available 'iPhone' | grep -E -o -i '([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})' | head -n 1)"
xcodebuild \
-workspace ZcashLightClientSample.xcworkspace \
-scheme ZcashLightClientSample \
-destination "id=$SIMULATOR_ID" \
clean \
build
```

The build command is a _very_ fancy way of saying "build it for an iOS Simulator on my machine" without having to assume an OS version or device that the host might have 😅,  Some inspiration from https://nshipster.com/simctl/
. Would be much nicer if it was possibe to something like`-destination "generic/platform=iOS Simulator"` but as far as I know this is not possible... please let me know if there is!

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2021-10-04 13:19 UTC, str4d commented on Scripts/build_librustzcash_xcode.sh
> +    cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release
Does this work? If I recall correctly, iOS requires that libraries used in apps be "universal" and target all iOS architectures. Has this changed?

2021-10-04 13:51 UTC, pacu commented
Travis CI Build is failing with 
````
=== BUILD TARGET ZcashLightClientKit OF PROJECT Pods WITH CONFIGURATION Debug ===
Building Rust backend
platform name
iphonesimulator
fix 'permission denied issue'
cargo +nightly build --manifest-path /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../Cargo.toml --target x86_64-apple-ios --release
export LIBRARY_PATH="/Applications/Xcode-12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib:"
error: toolchain 'nightly-x86_64-apple-darwin' is not installed
/Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../Scripts/build_librustzcash_xcode.sh: line 44: persist_environment: command not found
clean up existing artifacts: rm -f /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../ZcashLightClientKit/zcashlc/libzcashlc.a
clean up sdk lib path: rm -f /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../lib/libzcashlc.a
copying artifacts: cp -f /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../ZcashLightClientKit/zcashlc/libzcashlc.a
cp: /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a: No such file or directory
copying artifacts: cp -f /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../lib/libzcashlc.a
cp: /Users/travis/build/zcash/ZcashLightClientKit/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a: No such file or directory
** BUILD FAILED **
/Users/travis/.travis/functions: line 607:  4158 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "travis_wait 60 xcodebuild -quiet -UseModernBuildSystem=NO -workspace ./Example/ZcashLightClientSample/ZcashLightClientSample.xcworkspace -scheme ZcashLightClientSample -destination platform\=iOS\ Simulator,OS\=14.5,name\=iPhone\ 8 build" exited with 65.
````

2021-10-04 14:03 UTC, pacu commented
Bitrise CI is failing with this error 
 
 ````
▸ Running script '[CP-User] Build generate constants and build librustzcash'
❌  error: toolchain 'nightly-x86_64-apple-darwin' is not installed
Last lines of the Xcode's build log:
cp: /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a: No such file or directory
copying artifacts: cp -f /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../lib/libzcashlc.a
cp: /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a: No such file or directory
** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Build\ generate\ constants\ and\ build\ librustzcash /Users/vagrant/Library/Developer/Xcode/DerivedData/ZcashLightClientSample-bgjqxuwsktfenyabttyfngigqezy/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/ZcashLightClientKit.build/Script-C9462958FFCBCF2AA9566CCBDC027C0C.sh
(1 failure)
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Build failed, error: exit status 65
````

2021-10-04 14:03 UTC, pacu requested changes
@dh-ecc please review the comments from Str4d and the errors on CI

2021-10-04 14:18 UTC, str4d commented on Scripts/build_librustzcash_xcode.sh
> +    cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release
`cargo-lipo` was there because everything I read at the time indicated that iOS (or maybe it was just the app store?) wouldn't work with target-specific library builds. If that has changed, and app developers can produce several smaller target-specific apps like with Android, then yes there is no need for `cargo-lipo`.

2021-10-04 15:19 UTC, dh-ecc commented on Scripts/build_librustzcash_xcode.sh
> +    cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release
[@pacu]
> Should cargo lipo be removed? I'm not a rust expert so I don't know what's the right call

It's certainly fine in the current context of only needing to build for one target for a given host. We _will_ need to use `lipo` for the binary distribution, but I think it's probably preferable to move the task of creating universal binaries out of the rust toolchain and use `/usr/bin/lipo` directly... that's what I have been doing on [dh-ecc/ZcashRustLib.xcframework](https://github.com/dh-ecc/ZcashRustLib.xcframework) so far (though it is not automated just yet)

2021-10-05 15:51 UTC, nuttycom approved these changes
This looks good! cc58a21ad752fe7d314c4ec43d5a7dca1ffbe2c5 is the most recent commit on the librustzcash branch and I *hope* the commit that will actually be merged soon, but the commit you're at here should be fine.

2021-10-05 15:56 UTC, nuttycom commented on rust/src/lib.rs
> +            txout: txout,
```suggestion
            txout,
```

2021-10-05 16:16 UTC, pacu requested changes

2021-10-05 16:16 UTC, pacu commented on Cargo.toml
> +zcash_client_backend = {git = "https://github.com/nuttycom/librustzcash", rev = "da3c84ff31beec2c114729044d05bec3211a03d3" }
I Thought we were pointing these to the branch instead.

2021-10-05 16:16 UTC, pacu commented on Scripts/build_librustzcash_xcode.sh
> +echo "cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release"
@str4d suggested that we don't build nightly when the Xcode target is release. This would make every build, to run in nightly.

nightly should be used (for now) only for targets that require so. otherwise do it as always.

NOTE: This could be kind of confusing. The --release argument is for rust, which is fine and should be built that way, otherwise the rust compiler will run without optimizations.

2021-10-05 17:58 UTC, nuttycom commented on Cargo.toml
> +zcash_client_backend = {git = "https://github.com/nuttycom/librustzcash", rev = "da3c84ff31beec2c114729044d05bec3211a03d3" }
In my experience that causes more headaches than it saves, because you have to explicitly run `cargo update` to re-check whether you have the most recent commit on the targeted branch. Using commit hashes avoids the "works on my machine" problem.

2021-10-05 18:08 UTC, dh-ecc commented on Cargo.toml
> +zcash_client_backend = {git = "https://github.com/nuttycom/librustzcash", rev = "da3c84ff31beec2c114729044d05bec3211a03d3" }
good question, and possibly deferring to @nuttycom for help here:

I was having trouble with the very latest change, `https://github.com/zcash/librustzcash/pull/341/commits/cc58a21ad752fe7d314c4ec43d5a7dca1ffbe2c5` and I thought better to pin to a specific hash, but there is the trade off between a new commit breaking, or a rebase removing a reference 😅, which would you prefer? @nuttycom what are your thoughts here?

2021-10-05 18:47 UTC, dh-ecc commented on rust/src/lib.rs
> +        let txout = TxOut { value: Amount::from_i64(value).unwrap(), script_pubkey: script_pubkey };
done in 1e94f01

2021-10-05 18:47 UTC, dh-ecc commented on rust/src/lib.rs
> +            txout: txout,
done in 1e94f01

2021-10-05 19:09 UTC, dh-ecc commented on Scripts/build_librustzcash_xcode.sh
> +echo "cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release"
yeh this sounds like a good idea 👍 I'll add this change.

2021-10-05 20:10 UTC, dh-ecc commented on Cargo.toml
> +zcash_client_backend = {git = "https://github.com/nuttycom/librustzcash", rev = "da3c84ff31beec2c114729044d05bec3211a03d3" }
(wrote this comment before seeing https://github.com/zcash/ZcashLightClientKit/pull/316#pullrequestreview-771637258 which answers this with `1.` 😊 )

2021-10-05 20:11 UTC, dh-ecc commented on Scripts/build_librustzcash_xcode.sh
> +echo "cargo +nightly build --manifest-path ${PODS_TARGET_SRCROOT}/Cargo.toml --target $ZCASH_ACTIVE_ARCHITECTURE --release"
done in 7cec435.

2021-10-05 22:42 UTC, pacu commented
Bitrise is failing with

````
Running script '[CP-User] Build generate constants and build librustzcash'
    Patch `jubjub v0.7.0 (https://github.com/zkcrypto/jubjub.git?rev=96ab4162b83303378eae32a326b54d88b75bffc2#96ab4162)` was not used in the crate graph.
❌  error: could not compile `cfg-if` due to previous error
    build failed, waiting for other jobs to finish...
❌  error: build failed
Last lines of the Xcode's build log:
copying artifacts: cp -f /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../lib/libzcashlc.a
+ cp -f /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../lib/libzcashlc.a
cp: /Users/vagrant/git/Example/ZcashLightClientSample/Pods/../../../target/x86_64-apple-ios/release/libzcashlc.a: No such file or directory
** BUILD FAILED **
````

2021-10-06 19:19 UTC, dh-ecc commented
@pacu Bitrise is failing because it is building in `Release` configuration which builds all available platform architectures, since it's for simulator it will need to have an x86_64 and arm64 slice.

To sort this I reintroduced `cargo-lipo` 😅, this will be temporary since we'll remove _all_ of the rust tooling in the near future.

Would you be able to add a `cargo install cargo-lipo` to the bitrise setup (again 😓 sorry)?

2021-10-08 16:24 UTC, pacu requested changes

2021-10-08 16:24 UTC, pacu commented on Scripts/build_librustzcash_xcode.sh
> +    ZCASH_ACTIVE_ARCHITECTURE="aarch64-apple-ios-sim x86_64-apple-ios"
If I'm not mistaken this change would make the release builds to use nightly regardless, wouldn't it?

2021-10-11 16:24 UTC, pacu approved these changes

2021-10-11 16:24 UTC, merged