[WIP] Remove rust build phase
zcash/ZcashLightClientKit pull request #338
Opened 2022-01-26 11:51 UTC by dh-ecc

We now bring in a precompiled binary

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-01-26 15:24 UTC, pacu commented
There are many files that are listed as "renamed" but have no apparent change in their path 
![image](https://user-images.githubusercontent.com/484008/151192269-1eb128d8-c22c-43f4-a679-177b9c74d3d8.png)

2022-01-26 17:41 UTC, pacu requested changes
There are many files being deleted. the fork appears to be out of date.

2022-01-26 17:41 UTC, pacu commented on Package.swift
> +        .package(url: "https://github.com/stephencelis/SQLite.swift.git", from: "0.13.0"),
this library was 0.12.2 were test ran to verify that the changes did not break anything ?

2022-01-26 17:41 UTC, pacu commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+mainnet.swift
> +        case 1336316 ..< BlockHeight.max:
This file is reverting changes

2022-01-26 17:41 UTC, pacu commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+testnet.swift
> +                height: 1507328,
this file is reverting changes

2022-01-26 17:41 UTC, pacu commented on changelog.md
> -# 0.12.0-alpha.11
why is this file being deleted?

2022-01-26 17:41 UTC, pacu commented on docs/Architecture.md
> -# Architecture
Why is this file being deleted?

2022-01-26 17:41 UTC, pacu commented on docs/ci.md
> -# Continuous Integration
Why is this file being deleted?

2022-01-26 17:41 UTC, pacu commented on responsible_disclosure.md
> -This page is copyright The Electric Coin Company, 2021. It is posted in order to conform to this standard: https://github.com/RD-Crypto-Spec/Responsible-Disclosure/tree/d47a5a3dafa5942c8849a93441745f
Why is this file being deleted?

2022-01-26 17:41 UTC, pacu commented on docs/testing/manual_testing/README.md
> -
Why is this file being deleted?

2022-01-26 17:41 UTC, pacu commented on docs/testing/local_coverage.md
> -# Gathering Code Coverage
Why is this file being deleted?

2022-02-28 17:18 UTC, Daniel1of1 commented on DerivationToolTests/DerivationToolMainnetTests.swift
> -class DerivationToolMainnetTests: XCTestCase {
They're back now, this was temporary 😊.

2022-02-28 17:20 UTC, Daniel1of1 commented on Example/ZcashLightClientSample/Podfile
> +  pod 'MnemonicSwift', '~> 2.0.0'
I've moved from cocoapods to SPM for the Example project dependencies, though I might need to make sure it points to the hackworks fork. From what I can see it's building and running fine currently. Let me know if it should be changed.

2022-02-28 17:20 UTC, Daniel1of1 commented on README.md
> -[![Build Status](https://travis-ci.org/zcash/ZcashLightClientKit.svg?branch=master)](https://travis-ci.org/zcash/ZcashLightClientKit)
Back again 😊, and updated accordingly.

2022-02-28 17:20 UTC, Daniel1of1 commented on LICENSE
> -MIT License
Back again 😊

2022-02-28 17:21 UTC, Daniel1of1 commented on Package.swift
> +        .package(url: "https://github.com/stephencelis/SQLite.swift.git", from: "0.13.0"),
Yep this is working fine, IIRC it was necessary for arm64 simulator support, can double check.

2022-02-28 17:21 UTC, Daniel1of1 commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+mainnet.swift
> +        case 1336316 ..< BlockHeight.max:
Thanks! removed the change.

2022-02-28 17:22 UTC, Daniel1of1 commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+testnet.swift
> +                height: 1507328,
Good spot@, removed this change too!

2022-02-28 17:22 UTC, Daniel1of1 commented on changelog.md
> -# 0.12.0-alpha.11
File restored 😊

2022-02-28 17:22 UTC, Daniel1of1 commented on docs/Architecture.md
> -# Architecture
File restored 😊

2022-02-28 17:22 UTC, Daniel1of1 commented on docs/ci.md
> -# Continuous Integration
File restored 😊

2022-02-28 17:23 UTC, Daniel1of1 commented on responsible_disclosure.md
> -This page is copyright The Electric Coin Company, 2021. It is posted in order to conform to this standard: https://github.com/RD-Crypto-Spec/Responsible-Disclosure/tree/d47a5a3dafa5942c8849a93441745f
File restored 😊

2022-02-28 17:23 UTC, Daniel1of1 commented on docs/testing/manual_testing/README.md
> -
File restored 😊

2022-02-28 17:23 UTC, Daniel1of1 commented on docs/testing/local_coverage.md
> -# Gathering Code Coverage
File restored 😊

2022-02-28 17:25 UTC, dh-ecc commented on DerivationToolTests/DerivationToolMainnetTests.swift
> -class DerivationToolMainnetTests: XCTestCase {
Tests restored 😄 . See updated PR description for details.

2022-02-28 17:26 UTC, dh-ecc commented on README.md
> -[![Build Status](https://travis-ci.org/zcash/ZcashLightClientKit.svg?branch=master)](https://travis-ci.org/zcash/ZcashLightClientKit)
File Restored 👍

2022-02-28 17:26 UTC, dh-ecc commented on SWIFTLINT.md
> -# Swift Style Guide
File Restored 👍

2022-02-28 17:26 UTC, dh-ecc commented on LICENSE
> -MIT License
File Restored 👍

2022-02-28 17:27 UTC, dh-ecc commented on Package.swift
> +        .package(url: "https://github.com/stephencelis/SQLite.swift.git", from: "0.13.0"),
Yep, working fine as far as I can tell. IIRC I think this update was necessary for arm64 simulator support, I will double check this.

2022-02-28 17:27 UTC, dh-ecc commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+mainnet.swift
> +        case 1336316 ..< BlockHeight.max:
Thanks for catching this! I've undone the change.

2022-02-28 17:27 UTC, dh-ecc commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+testnet.swift
> +                height: 1507328,
Thanks for catching this! I've undone the change.

2022-02-28 17:29 UTC, dh-ecc commented on changelog.md
> -# 0.12.0-alpha.11
File restored! Though probably needs an update for the contents of this PR (though might make sense to add it separately after moving some of the repos we depend into zcash org and then tagging that release)

2022-02-28 17:29 UTC, dh-ecc commented on docs/Architecture.md
> -# Architecture
File Restored 👍

2022-02-28 17:29 UTC, dh-ecc commented on responsible_disclosure.md
> -This page is copyright The Electric Coin Company, 2021. It is posted in order to conform to this standard: https://github.com/RD-Crypto-Spec/Responsible-Disclosure/tree/d47a5a3dafa5942c8849a93441745f
File Restored 👍

2022-02-28 17:29 UTC, dh-ecc commented on docs/ci.md
> -# Continuous Integration
File Restored 👍

2022-02-28 17:29 UTC, dh-ecc commented on docs/testing/manual_testing/README.md
> -
File Restored 👍

2022-02-28 17:29 UTC, dh-ecc commented on docs/testing/local_coverage.md
> -# Gathering Code Coverage
File Restored 👍

2022-02-28 20:39 UTC, pacu commented
AdvancedReOrgTests passed
<img width="405" alt="image" src="https://user-images.githubusercontent.com/484008/156055225-3becb1c7-cb7b-4ede-8bb0-91474036a2b2.png">

2022-02-28 20:40 UTC, pacu approved these changes

2022-02-28 20:52 UTC, pacu commented
Approved overall. Requesting changes for 
> https://github.com/dh-ecc/libzcashlc should be moved to zcash org, and Podspec / package.swift files should be updated.
but using https://github.com/zcash-hackworks/zcash-light-client-ffi instead.


> It's fine not to publish, but we should move dh-ecc/CocoaPodsSpecs to zcash org

use this repository https://github.com/zcash-hackworks/CocoaPodsSpecs

2022-03-02 14:28 UTC, pacu requested changes
great work, please check minimum deployment target for package file

2022-03-02 14:28 UTC, pacu commented on Package.swift
> +        .iOS(.v13),
Current minimum deployment type for this SDK is 
` s.ios.deployment_target = '12.0'`

2022-03-02 17:21 UTC, dh-ecc commented on Package.swift
> +        .iOS(.v13),
👍 done in 3b6490c

2022-03-02 18:24 UTC, pacu approved these changes

2022-03-02 21:37 UTC, merged