0.13.0-beta.1 Update changelog.md and podspec version
zcash/ZcashLightClientKit pull request #345
Opened 2022-03-02 23:39 UTC by pacu

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-03-03 23:47 UTC, ccjernigan requested changes
It's super exciting to see the new release coming with SPM support.

Everything looks fine—this should work as-is.  I have some comments to improve performance and security of the github actions build though.

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +on: [push]
What's the desired behavior for when this runs?  For open pull requests?  After merge to main?

I suspect the desired implementation might be something like:
```
on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'changelog.md'
      - 'LICENSE'
      - 'README.md'
      - 'responsible_disclosure.md'
      - 'SWIFTLINT.md'
      - 'docs/**'
```

That would provide the behavior of running when a pull request is opened and when another commit is made to a pull request.  It will not run when certain documentation-only changes occur, reducing CI minutes used.  It also will not run when a merge is made to the main branch (assuming that merges to main are only done via pull request, so therefore don't need to be re-tested)

2022-03-03 23:47 UTC, ccjernigan commented on .travis.yml
> +    - swiftlint
Note that swiftlint isn't being pinned to a specific version.  It should be mostly OK, unless they add a new check that suddenly starts breaking our builds.  The last time I know this happened was about a year or so ago.  This could be something we consider filing a followup issue to improve.

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +    - uses: actions/checkout@v2
Checkout v3 just was released this week, so we can bump this version.

Also we can enhance security of this a bit by using the git SHA instead of the version.  The versions are really git tags, which means they could theoretically be changed.  GitHub has some buried documentation on this: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

It is top of mind, because this is a change I'll be making to the Android repos this coming week.

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +    - uses: actions/checkout@v2
https://github.com/actions/checkout/releases/tag/v3.0.0 so I think the SHA is `a12a3943b4bdde767164f792f33f40b04645d846 `

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
       timeout-minutes: 1
```

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +      run: swift build -v
Optional, although it might be worth considering an explicit timeout on the build steps.  If we get a bad runner or GitHub Actions is having an incident, sometimes builds can take forever and waste CI minutes.  Setting an explicit timeout creates some guardrails to keep the steps from running for too long.

The downside is that over time, we occasionally might have to increase the timeout as our codebase grows and builds take longer.

I chose the current suggested timeouts based on the run time of the action, plus some buffer.

```suggestion
    - name: Build
      timeout-minutes: 10
      run: swift build -v
```

2022-03-03 23:47 UTC, ccjernigan commented on .github/workflows/swift.yml
> +      run: swift test --filter OfflineTests
```suggestion
    - name: Run tests
      timeout-minutes: 5
      run: swift test --filter OfflineTests
```

2022-03-03 23:47 UTC, ccjernigan commented on changelog.md
> +- [Enhancement] Swift Package Manager Support!
🥳

2022-03-03 23:50 UTC, ccjernigan commented on .github/workflows/swift.yml
> +  build:
We can also harden the job a bit, by preventing the child steps from having write access to the repository.

    permissions:
      contents: read
```suggestion
  build:
      permissions:
          contents: read
```

2022-03-04 15:40 UTC, pacu commented on .travis.yml
> +    - swiftlint
Oh, I removed this and I'm installing swiftlint via homebrew and using the default xcode setting

2022-03-04 16:34 UTC, ccjernigan commented on .github/workflows/swift.yml
> +  build:
There's a minor syntax error that's failing the build.  Need `permissions:` e.g.
```
  build:
    permissions:
      contents: read
```

2022-03-04 16:34 UTC, ccjernigan commented on .travis.yml
> +    - swiftlint
Maybe I don't understand the Travis syntax.  I currently read this as using Homebrew to install sorcery and swiftlint.  Does Travis look up something in the Xcode project when invoking Homebrew to ensure a specific version of SwiftLint is used??

Or are you saying that because the .swiftlint configuration file is set, that it shouldn't introduce a breaking change?

The problem I encountered about a year ago was that I was using Apple's `masterClock` API for AVFoundation, and SwiftLint added a new check for the word "master" and then it broke my builds until I could update the .swiftlint file to bypass this check.

From what I understand, I don't think the current .swiftlint rules would prevent similar breaking changes in the future.

A solution to that would be to somehow pin a specific SwiftLint version, but I think we can file a followup issue since I don't expect this type of breakage to happen frequently.

2022-03-04 16:46 UTC, ccjernigan approved these changes

2022-03-04 16:48 UTC, pacu commented on .travis.yml
> +    - swiftlint
<img width="784" alt="image" src="https://user-images.githubusercontent.com/484008/156804367-00eb846e-f0ac-4b9e-a043-b1dddd98124b.png">
Yes, you are right.  This specific target Trivis is building does run swiftlint on a build phase. our usage of swift lint is not strict so it just warns you. 

If the version of homebrew is different (probable because the project one is outdated, since we use the version available on homebrew) it won't run but in terms of failure of success, it doesn't matter in this case.

2022-03-04 16:59 UTC, ccjernigan approved these changes

2022-03-04 17:22 UTC, merged