[#384] Adopt Type Safe Memos in the FFI and SDK
zcash/ZcashLightClientKit pull request #393
Opened 2022-06-10 20:40 UTC by pacu

Closes #384

This makes the SDK use the Memo and MemoBytes types across the FFI and the
public interface of the SDKSynchronizer. Addresses the comments by @defuse  on
issue https://github.com/zcash/ZcashLightClientKit/issues/378.
These changes depend on zcash-light-client-ffi repo changes managing
memos as byte arrays instead of string encoding of memos.

There are some compromises in terms of database representation of memos
and their exposure in transaction representing entities because we
wanted to avoid changing the database at this moment and be retro-
compatible with earlier versions and maintain deprecated APIs for wallets
to have time to adopt.

Memo and MemoBytes are WIP and subject to change. we are exploring
making Memo an opaque type based on a struct and drop the enum approach
to make the interface less throwing.

Fix: wrap new functions and deprecate old API. catch Memo errors

update get_sent and get_received memo functions from rust welding
point to branch in FFI repo

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-06-13 13:53 UTC, ccjernigan reviewed
I know a bit less about the memo and Rust internals.  Overall I think this looks like a good set of enhancements.  I had a few minor comments inline.

2022-06-13 13:53 UTC, ccjernigan commented on Package.resolved
> +          "branch": "make-memos-great-again",
😂

2022-06-13 13:53 UTC, ccjernigan commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +            memo: try! Memo(string: "test transaction"),
Why do two of these test cases use `try!` while the rest do not?

2022-06-13 13:53 UTC, ccjernigan commented on Tests/DarksideTests/BalanceTests.swift
> +                    XCTFail("failed retrieving memo from confirmed transaction. Errod: \(error.localizedDescription)")
Errord -> Error

```suggestion
                    XCTFail("failed retrieving memo from confirmed transaction. Error: \(error.localizedDescription)")
```

2022-06-13 13:53 UTC, ccjernigan commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +            memo: entity.memo == nil ? Data(MemoBytes.empty().bytes) : entity.memo,
What is the type of `entity.memo`?  Are we able to leverage the Optional extensions we have defined here?

2022-06-13 18:47 UTC, pacu commented on Tests/OfflineTests/PendingTransactionRepositoryTests.swift
> +        PendingTransaction(value: Int.random(in: 1 ... 1_000_000), toAddress: recipientAddress, memo: .empty(), account: 0)
Yes, I don't recall why I randomized this but, I doubt it can't be removed. Good catch. thanks!

2022-06-14 22:07 UTC, pacu commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +            memo: entity.memo == nil ? Data(MemoBytes.empty().bytes) : entity.memo,
not actually. this type is Data. Is kept that way so I don't have to change the underlying code :/

2022-06-15 19:02 UTC, pacu commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +            memo: entity.memo == nil ? Data(MemoBytes.empty().bytes) : entity.memo,
Unfortunately this is of type `Data`. I didn't want to change the underlying encoding so I didn't touch anything of the persistence layer since we will probably make more changes in the next sprints

2022-06-15 19:05 UTC, pacu commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +            memo: try! Memo(string: "test transaction"),
good catch! thanks

2022-06-27 16:58 UTC, str4d reviewed
I haven't reviewed the entire PR, just the pieces that interact with https://github.com/zcash-hackworks/zcash-light-client-ffi/pull/27.

2022-06-27 16:58 UTC, str4d commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        }
Ditto.

2022-06-29 18:20 UTC, defuse requested changes

2022-06-29 18:20 UTC, defuse commented on Sources/ZcashLightClientKit/Model/Memo.swift
>  }
There are a couple issues in `unpaddedRawBytes` above as well:

1. `firstNullByte` should be called `lastNullByte`.
2. I think this leaves one null byte in the string, because `...` is inclusive, when memo strings shouldn't ever end in a null byte (that's interpreted as padding and stripped away)

2022-06-29 18:20 UTC, defuse commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        guard let rawMemo = zcashlc_get_received_memo(dbData.0, dbData.1, idNote, networkType.networkId) else { return nil }
This code no longer works with the code in https://github.com/zcash-hackworks/zcash-light-client-ffi/pull/27/files#diff-f64796ccc388f201986ea7eaaf07bbefbd8ac1a56bb995fb505da80879872a39R862 (I think it's because str4d's suggestion was implemented there, but this code hasn't been updated yet)

2022-06-29 18:31 UTC, defuse commented on Sources/ZcashLightClientKit/Model/Memo.swift
>  }
That function might not handle the completely full memo case (no null bytes) properly. It seems like it would set `firstNullByte` to 512 and then try to `return [UInt8](bytes[0 ... firstNullByte])` which would try to access out-of-bounds memory.

I'm also confused what the `else { return [UInt8](bytes[0 ... 1]) }` is for, why do we want to return the first two bytes in that case? Or am I misunderstanding?

2022-06-29 18:33 UTC, defuse commented
Requested some bug fixes, overall this is a great improvement!

2022-06-30 10:22 UTC, LukasKorba approved these changes
same as Carter, I'm not so familiar with the layer but overall it LGTM. The try! has been already caught by Carter

2022-07-05 22:16 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        }
Good catch! Solved!

I'm creating a contiguous byte array of `MemoBytes.capacity` size and passing a mutable pointer to the rust function, then we copy those bytes (if successful) to the `MemoBytes` struct

2022-07-05 23:15 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Memo.swift
>          self = s
Uhmm. Pretty late to the party, I found this block form PSPDFKit about Swift and Null on character on Strings.
https://pspdfkit.com/blog/2020/null-character-strings/

If I understand correctly, we shouldn't be worried about a text string like `let string = "A\u{0}BC"` being passed to this initializer, but we should care about trimming trailing, null-bytes. Is that correct?

2022-07-06 18:37 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Memo.swift
>          self = s
@defuse Is this what you are referring to with this?

>Memo strings are still not allowed to contain null bytes at the end of the string, since those are considered to be padding and stripped away in the parsing. Instead of checking for null bytes anywhere, we should now be checking for null bytes at the end.

````Swift
func testTrimTrailingNullBytes() throws {
        let nullTrailedString = "This Is a memo with text and trailing null bytes\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}"

        let nonNullTrailedString = "This Is a memo with text and trailing null bytes"

        let trimmedString = String(nullTrailedString.reversed().drop(while: { $0 == "\u{0}"}).reversed())

        XCTAssertEqual(trimmedString, nonNullTrailedString)
    }
````

Shall null-trailed Strings be "sanitized" or should the constructor _throw_ an exception if trailing null-bytes are found?

2022-07-06 18:46 UTC, defuse commented on Sources/ZcashLightClientKit/Model/Memo.swift
>          self = s
> If I understand correctly, we shouldn't be worried about a text string like let string = "A\u{0}BC" being passed to this initializer, but we should care about trimming trailing, null-bytes. Is that correct?

Right.

With the way the API worked previously, we needed the...

```
        guard !string.containsCStringNullBytesBeforeStringEnding() else {
            throw MemoBytes.Errors.invalidUTF8
        }
...

...code to make sure that the memo won't be truncated. When we were using C strings to pass memos to the rust layer, any null byte would truncate the string. Now, with these changes, we don't have that problem, so we can delete this code.

Now, a memo is allowed to contain null bytes inside the string, but isn't allowed to contain null bytes at the end of the string, because technically those will be considered to be padding and will get cut off by the padding-stripper. So we need to check that:

```
let trimmedString = String(string.reversed().drop(while: { $0 == "\u{0}"}).reversed())
guard trimmedString == string else {
    throw MemoBytes.Errors.endsWithNullBytes
}
```

This will make sure that if someone tries to send a memo with trailing null bytes, it will fail for the sender, instead of it appearing to work and the trailing null bytes getting dropped on the receiver's side.

Now we need something like

2022-07-06 22:37 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Memo.swift
>  }
Thanks for pointing this out!

I made changes to avoid this and also added tests.

This function is kind of odd but works like this: 
1.  enumerate the byte array in an (index, byte) pair
2. reverse the enumerated sequence
3. get the index of the first non-null byte in the pair of the reversed enumerated sequence
4. return an array of the slice resulting of index 0 to the found index. Else return the first byte.

2022-07-06 23:33 UTC, pacu commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +        static var memo = Expression<Blob>("memo")
thanks! I should have reverted this!

2022-07-11 12:32 UTC, pacu commented
https://github.com/actions/virtual-environments/issues/5836 
awaiting for xcode 13.4.1 on github actions

2022-09-10 01:54 UTC, str4d approved these changes
utACK 0282d81584888009127174a49e196a6c6ec2f502 with a few questions.

2022-09-10 01:54 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> -    public func sendToAddress(
I'm assuming this was removed because it was left there to avoid changing the argument types, but now another argument is forced to change type so there's no benefit to further deprecation over removal.

2022-09-10 01:54 UTC, str4d commented on Sources/ZcashLightClientKit/Model/Memo.swift
> +        /// Invalid UTF-8 Bytes where detected when attempting to create a Text Memo
```suggestion
        /// Invalid UTF-8 Bytes were detected when attempting to create a Text Memo
```

2022-09-10 01:54 UTC, str4d commented on Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
> +                }
Does `MemoBytes.Errors.endsWithNullBytes` need to be special-cased here as well, or is it okay for that error case to fall through to the default catch?

2022-09-10 01:54 UTC, str4d commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +struct PendingTransaction: PendingTransactionEntity, Decodable, Encodable {
I don't know what this change is doing; it doesn't seem like it should affect memo usage.

2022-09-10 01:54 UTC, str4d commented on Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
> +            memo: entity.memo == nil ? Data(MemoBytes.empty().bytes) : entity.memo,
Elsewhere, I thought that optional `Data` was mapped to `MemoBytes.empty()` if not present. Does that mean `PendingTransaction.memo` can represent an empty memo as either `null` or `Data(MemoBytes.empty()`, or is `null` used for something else? I don't know if it matters that an empty memo can be represented in two ways within this part of the SDK.

2022-09-10 01:54 UTC, str4d commented on Tests/DarksideTests/BalanceTests.swift
> +            memo: try Memo(string: "this is a test"),
Is it intended that this memo stops having field substitutions?

2022-09-10 01:54 UTC, str4d commented on Tests/DarksideTests/BalanceTests.swift
> +            memo: try Memo(string: "this is a test"),
Same question here.

2022-09-10 02:41 UTC, merged