[#398] Make WalletBirthday an internal type
zcash/ZcashLightClientKit pull request #414
Opened 2022-07-12 16:35 UTC by pacu

This commit makes Renames `WalletBirthday` to `Checkpoint` and
makes Checkpoint an internal type. Public ocurrences of this
type is replaced by `BlockHeight` (Int) and then retrieval of the
Checkpoint is deferred to the appropiate place in the code

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-07-12 18:35 UTC, ccjernigan requested changes
This is a nice improvement!

I think there are a few filenames that should be updated.  I also noted a few things that we might defer for future enhancement, but wanted to raise them and get your opinion.

2022-07-12 18:35 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+Constants.swift
Do you want to rename the file too?

2022-07-12 18:35 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+mainnet.swift
>  //
Filename?

2022-07-12 18:35 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Constants/WalletBirthday+testnet.swift
Filename?

2022-07-12 18:36 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Initializer.swift
> +                height: Int32(checkpoint.height),
GitHub has been acting weird lately, hiding my own comments from me in the review interface if I leave the page 🙄

2022-07-12 18:49 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +                height: Int32(checkpoint.height),
Yeah, there's salad bar of int types we need to sort out. 

Changing the type was a huge change so I left it out on purpose.

2022-07-12 18:54 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Checkpoint.swift
> +    public private(set) var height: BlockHeight = -1
Oh thanks. I delete these values. we don't need them

2022-07-12 19:20 UTC, ccjernigan approved these changes

2022-07-12 19:36 UTC, merged

2022-07-28 13:31 UTC, str4d commented on Sources/ZcashLightClientKit/Model/Checkpoint.swift
> +/// time the wallet key was created. Worst case, the height of Sapling activation could be used (280000).
This is incorrect. Checkpoints store the state of the global commitment trees at the _end_ of a block; a checkpoint _cannot_ reference the earliest point in history where transactions related to this wallet can exist, because it is not possible to build witnesses for any notes received in the block corresponding to the checkpoint.

This suggests that the entire PR is subject to an off-by-one error (giving rise to a behaviour that @ccjernigan just asked about in Slack, where the SDK isn't downloading or scanning the checkpointed height; this behaviour is correct, because we cannot spend notes discovered at that height). If the intent is that the wallet birthday is allowed to be set by users to the first block containing transactions for this wallet, then the corresponding checkpoint height must be at most `birthday - 1`.

2022-07-28 13:33 UTC, str4d commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> -}
Ah, this type had the same documentation and issue. So the off-by-one was likely a pre-existing problem, that was just made more obvious by this PR.