Type safe address api
zcash/ZcashLightClientKit pull request #491
Opened 2022-08-21 16:21 UTC by pacu

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-08-23 10:54 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +public struct SaplingAddress: Equatable, StringEncoded {
Would it make sense to add a HeaderDoc for SaplingAddress explaining that it is a shielded address, which still works but that SDK developers should prefer UnifiedAddress when possible?

Alternatively, would it make sense to flag this as deprecated?  It wouldn’t mean that it is unsupported, just that UnifiedAddress is the preferred API now?

2022-08-23 21:50 UTC, pacu commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +public struct SaplingAddress: Equatable, StringEncoded {
this is a great catch

2022-08-27 00:24 UTC, pacu commented
@str4d  @nuttycom  I updated the code to this branch that builds `librustzcash_0_7` 

https://github.com/zcash-hackworks/zcash-light-client-ffi/tree/bin/librustzcash_0_7

Some of the tests to derive keys fail. 

````
  Assertions: Assertion Failure at DerivationToolTestnetTests.swift:99: XCTAssertEqual failed: ("UnifiedFullViewingKey(encoding: "uviewtest12tkgzhaevmw78us4xj2cx6ehxjgpp5da2qwrjqvytztejqfjdmy3e6nryqggtwrjum5cefuuuky8rscuw5dynmjec2tx3kkupqexw4va879pf874kvp6r8kjeza26gysxllaqwl67hm9u0jjke06zc93asrpw4wmy3g0lr9r5cy9pz49q2g7y7wm2pls5akmzhuvqr7khftk93aa2kpvwp7n3sjtmef28mxg3n2rpctsjlgsrhc29g6r23qc0u4tzd8rz8vqq4j7jxummdts8zx0jatzw4l2tl7r3egxhlw587rtkjx0y6dvw4hf4vjprn0qv3hs0sulmavk84ajeewn7argyerpr4essqvgfd0d24jpz6phxlasnd58qazh9d3yc6ad3hc5atp0pkvlq053zga65gscp0pv2plhqj9y2tcmx43thw5g4v8z3unytkc2dhyttuhmnlh5dyz4rmhgfkc96tp8z8rpfe35whjvky0jagz5n7qx", account: 0)") is not equal to 
("UnifiedFullViewingKey(encoding: "uviewtest16dqd5q7zd3xfxlcm2jm5k95zd92ed3qcm5jr9uq6yl5y2h6vuwfpxlnndckv5hpwsajgvq26xgdcdns8mqclecl0zh4sph45t4ncfnhcsus0k6sashfknsp9ltxrxlf096ljkwmp7psh3z2vmcd3rcc72qaujsl2y23ajexhr7qza29u9k95frs8qqgvy83rgymt7mmw09a02a5ytjpa502tshlsgl2j736jlfuzt27gezlajrs2tw9c99uqxrj5sx942vdr7w6yk2ltz96yq7n96fd9nr48c59dh9znqtwtm0nt9tmt7vzwhdwzt00tgp57mn85hpe6w00upmjv52kct9y", account: 0)")
  File: DerivationToolTestnetTests.swift:9

````


Also it appears that key validation functions don't produce errors when the key is semantically correct but belongs to a different network

````
func testSpendingKeyValidationThrowsWhenWrongNetwork() throws {
        XCTAssertThrowsError(try derivationTool.isValidExtendedSpendingKey("secret-extended-key-main1qw28psv0qqqqpqr2ru0kss5equx6h0xjsuk5299xrsgdqnhe0cknkl8uqff34prwkyuegyhh5d4rdr8025nl7e0hm8r2txx3fuea5mquy3wnsr9tlajsg4wwvw0xcfk8357k4h850rgj72kt4rx3fjdz99zs9f4neda35cq8tn3848yyvlg4w38gx75cyv9jdpve77x9eq6rtl6d9qyh8det4edevlnc70tg5kse670x50764gzhy60dta0yv3wsd4fsuaz686lgszc7nc9vv"))
    }
````

````
  Assertions: Assertion Failure at DerivationToolTestnetTests.swift:113: XCTAssertThrowsError failed: did not throw an error
  File: DerivationToolTestnetTests.swift:113
````

2022-08-29 16:24 UTC, nuttycom reviewed
Flushing comments.

2022-08-29 16:24 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        guard zcashlc_is_valid_sapling_extended_spending_key(key, networkType.networkId) else {
If we want to have network-incompatibility identified as a specific failure case that the SDK can recognize, we should change the implementation of this FFI call to return an integer value (0 for success, positive nonzero for "known" errors that the caller should handle, -1 for unrecoverable errors) instead. However, if we wanted to do that we'd have to change how we do parsing in librustzcash, because right now we discard the reason for the parse failure. @str4d do you have an opinion here? https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/address.rs#L203 swallows the specific error type; should we return `Result` from these methods instead?

2022-08-29 16:46 UTC, nuttycom approved these changes
utACK for the current unit of work to achieve an intermediate state that allows internal testing; however, I think that we should essentially change everything over to work in terms of unified keys before we publish a new release.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Throws: Error when the key is semantically valid  but it belongs to another network
I'm not sure how this can be identified as the specific validation error given how we're now doing the parsing, as mentioned before.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func deriveExtendedSpendingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedSpendingKey]?
```suggestion
    static func deriveSaplingExtendedSpendingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedSpendingKey]?
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func deriveExtendedFullViewingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedFullViewingKey]?
```suggestion
    static func deriveSaplingExtendedFullViewingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedFullViewingKey]?
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func deriveExtendedFullViewingKey(_ spendingKey: SaplingExtendedSpendingKey, networkType: NetworkType) throws -> SaplingExtendedFullViewingKey?
```suggestion
    static func deriveSaplingExtendedFullViewingKey(_ spendingKey: SaplingExtendedSpendingKey, networkType: NetworkType) throws -> SaplingExtendedFullViewingKey?
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func isValidExtendedSpendingKey(_ key: String, networkType: NetworkType) throws -> Bool
```suggestion
    static func isValidSaplingExtendedSpendingKey(_ key: String, networkType: NetworkType) throws -> Bool
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
>      static func isValidExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
```suggestion
    static func isValidSaplingExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func getShieldedAddress(accountIndex: Int) -> SaplingAddress?
```suggestion
    func getSaplingAddress(accountIndex: Int) -> SaplingAddress?
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    public func getShieldedAddress(accountIndex: Int) -> SaplingAddress? {
```suggestion
    public func getSaplingAddress(accountIndex: Int) -> SaplingAddress? {
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      func isValidShieldedAddress(_ zAddress: String) throws -> Bool
```suggestion
    func isValidSaplingAddress(_ zAddress: String) throws -> Bool
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func isValidExtendedSpendingKey(_ extsk: String) throws -> Bool
```suggestion
    func isValidSaplingExtendedSpendingKey(_ extsk: String) throws -> Bool
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveViewingKey(spendingKey: SaplingExtendedSpendingKey) throws -> SaplingExtendedFullViewingKey
```suggestion
    func deriveSaplingExtendedFullViewingKey(spendingKey: SaplingExtendedSpendingKey) throws -> SaplingExtendedFullViewingKey
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
```suggestion
    func deriveSaplingExtendedSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
```

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
I think it's a bit confusing to have these APIs take a number of accounts, whereas the `deriveTransparent*` methods take a single account identifier. My preference would be we change everything to work with single accounts, and that if multiple accounts are required that the caller make multiple calls. Same thing applies to `DeriveUnifiedFullViewingKeys`. Let's fix this now when we're overhauling a lot of stuff, rather than try to make a breaking change later.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifiedFullViewingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [UnifiedFullViewingKey] {
Same comment about the arity of the returned keys.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey] {
```suggestion
    public func deriveSaplingExtendedSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey] {
```
(Modulo return-arity issue)

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifiedAddress(seed: [UInt8], accountIndex: Int) throws -> UnifiedAddress {
I think this method needs to change so that the caller is required to provide the diversifier index; with unified addresses, we definitely want to avoid address reuse where possible.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifiedAddress(from ufvk: UnifiedFullViewingKey) throws -> UnifiedAddress {
Same comment here, we need to pass the diversifier index.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      public func deriveUnifiedAddressFromUnifiedFullViewingKey(_ ufvk: UnifiedFullViewingKey) throws -> UnifiedAddress {
Same comment here, pass the diversifier index.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAddressFromPublicKey(_ pubkey: String) throws -> TransparentAddress {
We need to think carefully about this method, and whether it should continue to exist. It's not clear here whether the pubkey is the account pubkey or the child ("diversified") pubkey. I think my recommendation is that we get rid of transparent and Sapling derivation methods entirely, and make all access to these kinds of legacy addresses route through the unified address derivation system: basically, derive a unified address, then extract the component you want.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> TransparentAccountPrivKey {
Same concern here, we should just get rid of this.

2022-08-29 16:46 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func isValidExtendedSpendingKey(_ extsk: String) throws -> Bool {
```suggestion
    public func isValidSaplingExtendedSpendingKey(_ extsk: String) throws -> Bool {
```

2022-08-29 23:05 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Throws: Error when the key is semantically valid  but it belongs to another network
This is important to catch a this particular user error.

2022-08-29 23:06 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public func getShieldedAddress(accountIndex: Int) -> SaplingAddress? {
tracked here
https://github.com/zcash/ZcashLightClientKit/issues/510

2022-08-29 23:08 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifiedAddress(seed: [UInt8], accountIndex: Int) throws -> UnifiedAddress {
tracked here

https://github.com/zcash/ZcashLightClientKit/issues/508

2022-08-29 23:09 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Throws: Error when the key is semantically valid  but it belongs to another network
Okay. We'll need to change this at least in the FFI layer then, if not in librustzcash itself.

2022-08-29 23:10 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
tracked here https://github.com/zcash/ZcashLightClientKit/issues/511

2022-08-30 19:12 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAddressFromPublicKey(_ pubkey: String) throws -> TransparentAddress {
I removed this since we do have other ways of deriving t-addresses

2022-08-30 19:15 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> TransparentAccountPrivKey {
we lack a series of APIs to actually extract these components from the unified keys

2022-08-30 21:18 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> TransparentAccountPrivKey {
Should we just accept the USK at the FFI layer for shielding, and then pass the transparent part of it?

I have a PR for the USK encoding almost ready.

2022-08-30 21:23 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> TransparentAccountPrivKey {
I think that we can worry about that in a subsequent PR

2022-08-30 23:00 UTC, pacu commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    var sapling: SaplingAddress? {
I removed this since it's future coding

2022-08-30 23:02 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Throws: Error when the key is semantically valid  but it belongs to another network
that's ok. I'll track that here https://github.com/zcash/ZcashLightClientKit/issues/509

2022-09-01 13:05 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
> +            loggerProxy.error("NO SPENDING KEY")
Too many force unwraps. I know it's the sample code, not a blocking request but I would rather use optional unwrapping.

2022-09-01 13:09 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +        zatoshi: Int,
NOTE: Feedback without too much context. Why Int and not a Zatoshi type?

2022-09-01 13:10 UTC, LukasKorba approved these changes
Added only a few non-blocking comments, otherwise LGTM

2022-09-06 15:13 UTC, nuttycom requested changes
This is looking good; there are just a few more things that need to be addressed.

2022-09-06 15:13 UTC, nuttycom commented on Sources/ZcashLightClientKit/Transaction/TransactionManager.swift
> +        result: @escaping (Result<PendingTransactionEntity, Error>) -> Void
Just a style question here: should there be a separate type for like a `SubmittableTransactionEntity` or something like that, so that the data flow is clearer? Right now, from the types it looks like you could just try to call `submit` with a `PendingTransactionEntity` that hasn't yet been encoded; it would be nice for the fact that that would fail to be encoded in the types.

2022-09-06 15:13 UTC, nuttycom commented on Tests/OfflineTests/RecipientTests.swift
> +    let uaString = "u1l9f0l4348negsncgr9pxd9d3qaxagmqv3lnexcplmufpq7muffvfaue6ksevfvd7wrz7xrvn95rc5zjtn7ugkmgh5rnxswmcj30y0pw52pn0zjvy38rn2esfgve64rj5pcmazxgpyuj"
General question: how were these test UA strings derived? It would potentially be a useful thing if these were taken from  the test vectors: https://github.com/zcash-hackworks/zcash-test-vectors/blob/master/test-vectors/json/unified_address.json

2022-09-06 18:35 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            guard let uAddr = self.getUnifiedAddress(accountIndex: accountIndex) else {
This can be a temporary resolution, so  long as nothing is actually depending upon that address being the address that funds are actually sent to. :grimacing:

2022-09-06 21:40 UTC, str4d commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    public var account: UInt32
Currently my belief is that it isn't really part of the public API, because `UnifiedFullViewingKey` is only used in these places:
- As an intermediary between `DerivationTool.deriveUnifiedFullViewingKeysFromSeed` and `ZcashRustBackend.initAccountsTable` (which itself is internal, but is reachable I think publicly via other pathways?).
- To derive UAs in `DerivationTool`, which again is just an intermediary step.
- In tests that check `DerivationTool`.

That's it AFAICT.

If this type is intended to be part of the public API then removing `account` makes sense, and we'd alter `ZcashRustBackend.initAccountsTable` to take a list of `(accountId, UnifiedFullViewingKey)` tuples.

Extending the public API to be a general shielded transaction toolkit isn't really the domain of this SDK, which specifically presents a simplified interface to creating and managing a wallet. I think the correct place for these kinds of APIs would be a sub-library (either one used by this SDK, or next to it).

2022-09-06 22:08 UTC, nuttycom commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    public var account: UInt32
Opened https://github.com/zcash/ZcashLightClientKit/issues/522 to track this.

2022-09-06 22:10 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            guard let uAddr = self.getUnifiedAddress(accountIndex: accountIndex) else {
Linking https://github.com/zcash/ZcashLightClientKit/issues/521 for discoverability.

2022-09-06 22:12 UTC, nuttycom approved these changes
utACK; additional required changes are tracked as https://github.com/zcash/ZcashLightClientKit/issues/521 and https://github.com/zcash/ZcashLightClientKit/issues/522

2022-09-07 15:20 UTC, merged