[463] Migrate LightwalletService to Async/Await
zcash/ZcashLightClientKit pull request #493
Opened 2022-08-22 12:03 UTC by LukasKorba

Closes #463 

- migration of the protocol's methods done
- split the code so there's blocking and non-blocking API separately
- async throws unit tests added
- sample app updated to the latest API

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-08-23 10:53 UTC, pacu requested changes

2022-08-23 10:53 UTC, pacu commented on Sources/ZcashLightClientKit/Service/ProtoBuf/service.grpc.swift
> +internal protocol CompactTxStreamerProvider: CallHandlerProvider {
This is the generate code for the server side. You should generate only client code. There's a flag on the generator `client=true`

2022-08-23 10:53 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +            blocks.append(ZcashCompactBlock(compactBlock: block))
Beware that this catches the whole range and returns a sequence where what we need is an async sequence.

2022-08-23 10:58 UTC, pacu commented
CI error:

````
❌  /Users/travis/build/zcash/ZcashLightClientKit/Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift:94:33: cannot find type 'CompactTxStreamerAsyncClient' in scope
    let compactTxStreamerAsync: CompactTxStreamerAsyncClient
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

2022-08-23 21:49 UTC, pacu requested changes

2022-08-23 21:49 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +        return blocks
This should return an AsyncSequence that let's the caller receive the updates block by block

The documentation is not quite clear tbh. The most similar example on the [Swift-GRPC documentation is the bi-directional streaming sample ](https://github.com/grpc/grpc-swift/blob/main/docs/basic-tutorial.md#bidirectional-streaming-rpc-1)

The examples point to receiving a Stream that implements the protocol AsyncSequence https://github.com/grpc/grpc-swift/blob/main/Sources/GRPC/AsyncAwaitSupport/GRPCAsyncResponseStream.swift

````
internal func getBlockRange(
    _ request: BlockRange,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<CompactBlock> {
    return self.performAsyncServerStreamingCall(
      path: CompactTxStreamerClientMetadata.Methods.getBlockRange.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBlockRangeInterceptors() ?? []
    )
  }
  ````
  This should be mapped into an AsyncSequence that the caller can traverse asynchronously that includes progress and the blocks

2022-08-23 21:49 UTC, pacu commented on Sources/ZcashLightClientKit/Service/ProtoBuf/service.grpc.swift
> +internal protocol CompactTxStreamerProvider: CallHandlerProvider {
On a second thought I'm unsure of this being true. Would you double-check? 

I don't think we need the interceptor code either. Can the swift-protoc-gen suppress that?

2022-08-24 14:21 UTC, pacu requested changes

2022-08-24 14:21 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +        return blocks
ps:
I’m not sure that what I did originally with the progress at LightWalletService is correct since the caller knows the range and it can calculate the progress itself

In our case the compact blocks do have a height that we use to track the progress

2022-08-24 14:21 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +    public func fetchUTXOsAsync(for tAddress: String, height: BlockHeight) async throws -> [UnspentTransactionOutputEntity] {
This also applies to GetBlockRange, but let's tackle this example since it's easier.

There's something called `AsyncStreams<Element>`

This is probably what we want for streaming calls. We wrap the GRPC stuff into an AsyncStream that we control and belongs to our domain.

2022-08-25 12:08 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +        return try compactTxStreamer.getLatestBlock(ChainSpec()).response.wait()
it doesn't, removed

2022-08-25 12:09 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Service/ProtoBuf/service.grpc.swift
> +internal protocol CompactTxStreamerProvider: CallHandlerProvider {
with the `protoc --grpc-swift_opt=Server=false --swift_out=. --grpc-swift_out=. service.proto` the whole block is no longer part of the grpc and SDK is buildable

2022-08-25 12:17 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +    public func fetchUTXOsAsync(for tAddress: String, height: BlockHeight) async throws -> [UnspentTransactionOutputEntity] {
reimplemented to use AsyncStream

2022-08-25 13:39 UTC, pacu approved these changes

2022-08-25 13:39 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift
>      private var cancelable: CancellableCall?
I think this is not being used

2022-08-25 13:40 UTC, merged