[476] CompactBlockProcessor to async/await
zcash/ZcashLightClientKit pull request #519
Opened 2022-09-06 09:21 UTC by LukasKorba

Closes #476 

- The Operation Queue has been removed from the code and tests
- processNewBlocks() async
- All ZcashOperations removed
- [BUGFIX] fail(error) was called even for canceled tasks but that must be excluded
- network tests in building and success order again
- offline tests in building and success order

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-09-06 21:17 UTC, pacu requested changes
Great work! I have some observations of CompactBlockProcessor state that we need to look at and handle

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
> +internal extension CompactBlockProcessor {
According to Swift's documentation internal is the default access level so it shouldn't be necessary to make it explicit.

from https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html
>Default Access Levels
All entities in your code (with a few specific exceptions, as described later in this chapter) have a default access level of internal if you don’t specify an explicit access level yourself. As a result, in many cases you don’t need to specify an explicit access level in your code.

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
> +            for index in 0 ..< transactions.count {
[Improvement] I think we should check cancellation more regularly here or in line 77. We originally thought of enhancement being a brief operation but since wallets are so backed down on syncing, it may not be

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    internal var storage: CompactBlockStorage
Same as above. Internal should be the default access

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> -    private var operationQueue: OperationQueue = {
🎊

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public internal(set) var state: State = .stopped {
This var is modified from many async tasks. Probably a good candidate for an `actor` model

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +/*
Is this comment preserved for some reason or can we delete it?

2022-09-06 21:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +            //self.fetchedUTXOsHandler?(result)
delete comment

2022-09-06 21:17 UTC, pacu commented on Tests/NetworkTests/CompactBlockProcessorTests.swift
> +//                startedScanningNotificationExpectation,
delete comments

2022-09-06 21:17 UTC, pacu commented on Tests/NetworkTests/DownloadTests.swift
> +            XCTFail("Donwload failed with error: \(error)")
```suggestion
            XCTFail("Download failed with error: \(error)")
```

2022-09-07 12:13 UTC, LukasKorba commented on Tests/NetworkTests/DownloadTests.swift
> +            XCTFail("Donwload failed with error: \(error)")
fixed

2022-09-07 12:13 UTC, LukasKorba commented on Tests/NetworkTests/CompactBlockProcessorTests.swift
> +//                startedScanningNotificationExpectation,
deleted

2022-09-07 12:14 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +            //self.fetchedUTXOsHandler?(result)
deleted

2022-09-07 12:15 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +/*
deleted

2022-09-07 12:17 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
> +internal extension CompactBlockProcessor {
removed

2022-09-07 12:18 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    internal var storage: CompactBlockStorage
removed

2022-09-07 12:18 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> -    private var operationQueue: OperationQueue = {
a milestone ;)

2022-09-07 12:21 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
> +            for index in 0 ..< transactions.count {
good to know, I added it to the while loop

2022-09-09 14:51 UTC, pacu reviewed
Just a minor comment here on a test

2022-09-09 14:51 UTC, pacu commented on Tests/NetworkTests/CompactBlockProcessorTests.swift
> -                startedValidatingNotificationExpectation,
Why did you have to remove these?

2022-09-12 06:49 UTC, LukasKorba commented on Tests/NetworkTests/CompactBlockProcessorTests.swift
> -                startedValidatingNotificationExpectation,
I don't know what's wrong but I see this:

```swift
func testStartNotifiesSuscriptors() {
        startProcessing()
   
        wait(
            for: [
                downloadStartedExpect,
                startedValidatingNotificationExpectation
            ],
            timeout: 30,
            enforceOrder: true
        )
    }
```
so the `startedValidatingNotificationExpectation` is still in place.

2022-09-12 06:54 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
> +        self.state = .downloading
After long investigation how to do it properly I decided to use NSLock instead of an Actor. Reasoning:

An Actor is expected to work in an async context but state in SDK is used in both sync and async context. Any modification of actor's variables must be awaited and that would mean to massively change the whole CompactBlockProcessor.

Just one example:
```swift
public func start(retry: Bool = false) throws {
        if retry {
            self.retryAttempts = 0
            self.processingError = nil
            self.backoffTimer?.invalidate()
            self.backoffTimer = nil
        }

        guard shouldStart else {
            switch self.state.getState() {
            case .error(let e):
                // max attempts have been reached
                LoggerProxy.info("max retry attempts reached with error: \(e)")
                notifyError(CompactBlockProcessorError.maxAttemptsReached(attempts: self.maxAttempts))
                setState(.stopped)
            case .stopped:
                // max attempts have been reached
                LoggerProxy.info("max retry attempts reached")
                notifyError(CompactBlockProcessorError.maxAttemptsReached(attempts: self.maxAttempts))
            case .synced:
                // max attempts have been reached
                LoggerProxy.warn("max retry attempts reached on synced state, this indicates malfunction")
                notifyError(CompactBlockProcessorError.maxAttemptsReached(attempts: self.maxAttempts))
            default:
                LoggerProxy.debug("Warning: compact block processor was started while busy!!!!")
            }
            return
        }

        self.nextBatch()
    }
```

Current NSLock solution allow us to create set and get methods and use it in both sync and async contexts like this
```swift
self.state.getState()
```

while an Actor would force us to write
```swift
await self.stateActor.state
```
meaning the start() method would need to be async or wrapped in Task. And that is just one example of many other cases.

2022-09-12 06:55 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public internal(set) var state: State = .stopped {
see the comment https://github.com/zcash/ZcashLightClientKit/pull/519#discussion_r968043103

2022-09-12 15:26 UTC, pacu requested changes
I'm not convinced with the mutex implementation. According to what one can see in Apple docs and other resources, actors should be sufficient to provide the functionality we need for the state.

2022-09-12 15:26 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift
> +        setState(.scanning)
If the thread safe State was an actor, this setter would be run on the actor's queue, supposedly achieving the same effect as the lock you implemented

2022-09-14 06:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public class ThreadSafeState {
TODO added with the explanation and link to the Actor's ticket

2022-09-14 06:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift
> +        setState(.scanning)
TODO added with the explanation and link to the Actor's ticket

2022-09-14 18:57 UTC, pacu requested changes
Overall looks good. I have two questions around Tasks and their priorities.

2022-09-14 18:57 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
> +        let task = Task(priority: .userInitiated) {
Why is this Task spun up inside an async function?

2022-09-14 18:57 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        cancelableTask = Task {
shouldn't this be `.userInitiated` ?

2022-09-15 06:07 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
> +        let task = Task(priority: .userInitiated) {
Considered the 2nd comment I think we can get rid of this and encapsulate whole processNewBlocks in one task with priority .userInitiated, updated

2022-09-15 06:09 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        cancelableTask = Task {
updated so the `nextBatch()` is MainActor Task while processing new blocks encapsulates all logic in another Task with `.userInitiated` priority.

2022-09-15 13:03 UTC, pacu approved these changes

2022-09-15 13:04 UTC, pacu commented
I reviewed and ran the AdvancedReOrg tests on this PR successfully

2022-09-15 13:08 UTC, merged