Use UnifiedSpendingKey for shielding and Spending
zcash/ZcashLightClientKit pull request #535
Opened 2022-09-19 23:59 UTC by pacu

Closes #534 

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-09-20 15:38 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
>      static func deriveTransparentAddressFromSeed(
Same with this?

2022-09-20 15:38 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
>      static func deriveTransparentAccountPrivateKeyFromSeed(
And this.

2022-09-22 17:34 UTC, nuttycom requested changes
Overall, most of these comments are minor. However, I have one more substantive design suggestion: I think that the `ZcashRustBackendWelding` API should be constructed in a more object-oriented fashion, where the methods are focused on the domain operations, and the `dataDb`, various spend parameter paths, and network information all be provided to a fallible function that constructs the object that represents the capability to perform these operations. As a secondary benefit to this approach, the data db initialization call could be performed as part of this constructor function.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifierFullViewingKey(from spendingKey: UnifiedSpendingKey) throws -> UnifiedFullViewingKey {
```suggestion
    public func deriveUnifiedFullViewingKey(from spendingKey: UnifiedSpendingKey) throws -> UnifiedFullViewingKey {
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// clears the cached utxos for the given address from the specified height on
Can you add a little bit of documentation about how/when this is supposed to be used?

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// automated account recovery).table from a given seed and a number of accounts
```suggestion
    /// automated account recovery).
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///  - Returns: The `UnifiedSpendingKey` structs for the number of accounts created
Missing `networkType`

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Parameter usk: `UnifiedSpendingKey`y for the account the spend will be done from
```suggestion
    /// - Parameter usk: `UnifiedSpendingKey` for the account that controls the funds to be spent.
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Parameter outputParamsPath: path escaped String for the filesystem locations where the output parameters are located
An API question: it seems like `dbData`, `spendParamsPath`, and `outputParamsPath` (and maybe `networkType`) could all be member variables of an object, and then `createToAddress` could just be a method that takes the USK, the address, the value and the memo. 

I like to separate things that are configuration-oriented from business logic in my applications; I'm not sure if that applies here.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// the rewind can't be more than 100 block or back to the oldest unspent note that this wallet contains.
```suggestion
    /// the rewind can't be more than 100 blocks or back to the oldest unspent note that this wallet contains.
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// Returns the nearest height where a rewind is possible. Currently prunning gets rid of sapling witnesses older
```suggestion
    /// Returns the nearest height where a rewind is possible. Currently pruning gets rid of sapling witnesses older
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func getNearestRewindHeight(dbData: URL, height: Int32, networkType: NetworkType) -> Int32
It's not entirely clear to me from the documentation how this is intended to be used. Is this basically just so that one can guard a rewind operation? If so, should we alternately consider and API that simply attempts a rewind, and does this check internally (and returns a failure if the requested rewind can't be performed?)

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func getSentMemo(
Should we consider unifying the `getSentMemo` and `getReceivedMemo` APIs? It seems like this is something that should be handled on the backend.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func getTransparentReceiver(for uAddr: UnifiedAddress) throws -> TransparentAddress
Should this instead return a `TransparentAddress?`, and only throw if the UA is invalid? That seems like the more appropriate way to separate concerns; it's not an error that a UA doesn't contain a transparent receiver.

Nit: I would group this with the `getSaplingReceiver` function.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func getSaplingReceiver(for uAddr: UnifiedAddress) throws -> SaplingAddress
I think that this should return `SaplingAddress?` instead. It's not an error to not have a Sapling receiver on a UA.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// initialize the accounts table from a set of unified full viewing keys
I would document that is is essentially only intended for situations where you're restoring from seed, and that `createAccount` should be used otherwise.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// initializes the data db
Document that this will perform the migrations required to update the data database to have the required schema and contents.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - saplingTree: hash of the sapling tree
Missing `networkType`

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// initialize the blocks table from a given checkpoint (birthday)
I don't see an argument that can be used to provide the birthday height? Or is `birthday` the wrong term here?

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// rewinds the compact block storage to the given height. clears up all derived data as well
This documentation is a little confusing, because I think of the "compact block storage" as the cache db. 
```suggestion
    /// Resets the state of the database to only contain block and transaction information up to the 
    /// specified height.
```

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// rewinds the compact block storage to the given height. clears up all derived data as well
I think that this should also document what happens if the user has sent transactions in blocks that would be invalidated by this rewind.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - height: height to rewind to. DON'T PASS ARBITRARY HEIGHT. Use getNearestRewindHeight when unsure
As suggested above, I don't think that this should be two calls; instead, the rewind should return failure if too large of a rewind is requested. Maybe the height parameter should be optional, and then if it's not provided the `getNearestRewindHeight` call should be done internally?

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - limit: scan up to limit blocks. pass 0 to set no limit.
Missing documentation for the `networkType` parameter.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// [`zcashlc_init_blocks_table`] before this function.
`zcashlc_init_blocks_table` shouldn't be mentioned here explicitly.

2022-09-22 17:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Parameter usk: `UnifiedSpendingKey` that spend transarent funds and where the funds will be shielded to.
Document that this must correspond to the provided account. If your `UnifiedSpendingKey` model contains account information, then the `account` parameter should be omitted at this layer entirely.

2022-09-22 17:40 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        address: String,
Does this make sense to go address-by-address? Or should the transparent balance be returned on an account-by-account basis?

I guess that per-address is relevant because we want shielding operations to usually not shield across multiple transparent addresses, because doing so links the associated UAs as belonging to the same wallet.

2022-09-22 19:49 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - Parameter outputParamsPath: path escaped String for the filesystem locations where the output parameters are located
I think these suggestions make sense but are out of scope of what we are trying to achieve at the moment

2022-09-22 19:52 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        address: String,
I think that the balance makes sense on an account basis. But I've never thought of shielding in terms of rolling addresses. Would grabbing all the funds from all addresses and shielding them provide insight on those addresses? OTOH, wouldn't fragmenting per-address eventually make a shielding threshold unreachable?

2022-09-22 19:53 UTC, pacu commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    public func deriveUnifierFullViewingKey(from spendingKey: UnifiedSpendingKey) throws -> UnifiedFullViewingKey {
I need to do a rename all. It's pending. thanks

2022-09-23 14:00 UTC, nuttycom commented on Package.swift
> +        .package(name:"libzcashlc", url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", branch: "bin/librustzcash_0_7")
Would it make sense to use an explicit hash reference, rather than a branch ID? I think that would make things a little easier with Xcode, because then when that hash changes xcode will know it needs to fetch the new version?

2022-09-27 14:26 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Initializer.swift
> +//    }
do we want to keep the commented out code here?

2022-09-27 14:32 UTC, LukasKorba approved these changes
LGTM.. just a small non-blocking comment, haven't run the tests though

2022-09-28 16:34 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +//    }
nope! thanks!

2022-09-28 19:12 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - height: height to rewind to. DON'T PASS ARBITRARY HEIGHT. Use getNearestRewindHeight when unsure
Do you mean something like this? (note: I haven't tested this)

````Swift
static func rewindToHeight(
        dbData: URL,
        height: Int32?,
        networkType: NetworkType
    ) throws -> Bool {
        let nearestRewind = getNearestRewindHeight(dbData: dbData, height: 0, networkType: networkType)

        let dbData = dbData.osStr()


        if let height = height {
            guard height < nearestRewind else {
                throw RustWeldingError.invalidRewind(suggestedHeight: nearestRewind)
            }

            return zcashlc_rewind_to_height(dbData.0, dbData.1, height, networkType.networkId)
        } else {
            return zcashlc_rewind_to_height(dbData.0, dbData.1, nearestRewind, networkType.networkId)
        }
    }
````

2022-09-28 19:49 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        address: String,
Ok I implemented the account based transparent balance that addresses this

2022-09-28 19:49 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    static func getSentMemo(
probably out of scope for now

2022-09-28 19:50 UTC, pacu commented on Package.swift
> +        .package(name:"libzcashlc", url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", branch: "bin/librustzcash_0_7")
Xcode hates us 😹

2022-09-28 19:56 UTC, nuttycom commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get Address/GetAddressViewController.swift
> +    @IBOutlet weak var saplingAddress: UILabel! // THIS SHOULD BE SUPER SECRET!!!!!
This comment is no longer valid.

2022-09-28 20:43 UTC, nuttycom requested changes
Just a couple more changes, and https://github.com/zcash-hackworks/zcash-test-vectors/pull/90 should have the updated test vectors that you need to make the remainder of the tests work.

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        return true
nit: I think that this would read more clearly as:
```suggestion
        let result = zcashlc_is_valid_viewing_key([CChar](key.utf8CString), networkType.networkId)
        if let error = lastError() {
            throw error
        } else {
            return result
        }
```

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        guard zcashlc_is_valid_sapling_extended_spending_key([CChar](key.utf8CString), networkType.networkId) else {
Same comment here about the use of `guard` when returning boolean values in general.

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            guard try self.isValidUnifiedFullViewingKey(ufvk.encoding, networkType: networkType) else { // TODO Fix
What is this TODO about?

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            throw RustWeldingError.dataDbInitFailed(message: "Unknown Error")
This seems like a programming error rather than an initialization failure, isn't it? Should this be an assertion instead? Is `lastError` expected to be fallible in such a way that it requires this fallback?

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        address: String,
nit: it'd be nice to have a better type for transparent addresses.

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        to address: String,
This on the other hand really is a polymorphic address string.

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - height: height to rewind to. DON'T PASS ARBITRARY HEIGHT. Use getNearestRewindHeight when unsure
Yes, that looks good.

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - index: the index of the UTXO
The `script` argument is not documented

2022-09-28 20:43 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            let tBalance = try self.getTransparentBalance(accountIndex: accountIndex)
This is fine for now; we'll need to rework shielding according to ZIP 315 later.

2022-09-28 22:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        getUnifiedAddres(accountIndex: accountIndex)?.transparentReceiver()
Oh thanks! I had changed that but apparently I lost that change somehow

2022-09-29 18:20 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +            )
yep. that's done!

2022-09-29 18:35 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        return UnifiedAddress(validatedEncoding: address, network: networkType)
It is but I had to include it because the underlying functions need it. Having an environment variable that hits 2 or 3 calls deep it's even worse than including the network type.

2022-09-29 21:30 UTC, nuttycom approved these changes
utACK with one minor comment: would it be easier to avoid the build failures if we did something like this in `Package.swift` instead?

```
-        .package(name:"libzcashlc", url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", branch: "bin/librustzcash_0_7")
+        .package(name:"libzcashlc", url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", revision: "e8fbb84c1bec44af9dbef7e27c85f25e8f51a5af")
```

2022-09-29 21:42 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            throw RustWeldingError.dataDbInitFailed(message: "Unknown Error")
It depends on code that it's nullable from the C bindings. I'd rather have this unknown error to catch a weird malformed error from Rust than crashing the client application

2022-09-29 22:12 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        address: String,
should this be account based as well?

2022-09-29 22:22 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        address: String,
should this be account based now?

2022-09-29 22:26 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    ///   - height: height to rewind to. DON'T PASS ARBITRARY HEIGHT. Use getNearestRewindHeight when unsure
opened this issue

https://app.zenhub.com/workspaces/wallet-5db8aa0244512d0001e0968e/issues/zcash/zcashlightclientkit/548

2022-09-29 22:29 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
>      public func getUnifiedAddres(accountIndex: Int) -> UnifiedAddress? {
The compact block processor is basically a lower level synchronizer. 
The synchronizer is aware of OS dependent events that the processor shouldn't care about. Addresses are not affected by that. That's why it had these methods

2022-09-29 22:29 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        return UnifiedAddress(validatedEncoding: address, network: networkType)
resolved

2022-09-29 22:34 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> -    static func lastError() -> RustWeldingError?
I'm not sure that this is the correct change; the type of this now implies that some error must have occurred. It is a little more ergonomic, perhaps, but it doesn't seem right from a type perspective.

2022-09-29 22:35 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            return RustWeldingError.dataDbInitFailed(message: "Unknown Error")
`dataDbInitFailed` doesn't seem like the right error here.

2022-09-30 13:47 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> -    static func lastError() -> RustWeldingError?
I think this got unresolved by the force-push.

2022-09-30 13:49 UTC, nuttycom requested changes
The change to `lastError` doesn't make sense to me. Let's discuss.

2022-09-30 21:00 UTC, nuttycom approved these changes
utACK

2022-10-03 02:10 UTC, pacu commented
`testReOrgRemovesOutboundTxAndIsNeverMined` test fixed

2022-10-03 02:11 UTC, merged