[#492] Get rid of blocking API
zcash/ZcashLightClientKit pull request #551
Opened 2022-09-30 13:27 UTC by LukasKorba

Closes #492 

- blocking API removed, only latestBlockHeight() stayed
- non-blocking closure based API removed
- unit tests updated to use async API

<img width="368" alt="Screenshot 2022-09-30 at 15 26 59" src="https://user-images.githubusercontent.com/7198042/193279924-eb1ff91e-033d-46c5-9e01-654355c6097a.png">

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-10-02 22:57 UTC, pacu requested changes
requesting some changes  on comments and commented code

2022-10-02 22:57 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletService.swift
>      /// - Parameter result: escaping closure that takes a result containing either LightWalletServiceResponse or LightWalletServiceError
```suggestion
 
```

2022-10-02 22:57 UTC, pacu commented on Sources/ZcashLightClientKit/Service/LightWalletService.swift
>      /// - Parameter result: handler for the result
```suggestion
```

2022-10-02 22:57 UTC, pacu commented on Tests/TestUtils/FakeService.swift
> +//    }
```suggestion
```

2022-10-02 22:57 UTC, pacu commented on Tests/TestUtils/FakeService.swift
> +//    }
```suggestion
```

2022-10-03 10:40 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Service/LightWalletService.swift
>      /// - Parameter result: escaping closure that takes a result containing either LightWalletServiceResponse or LightWalletServiceError
There were other result parameters, I cleaned up all

2022-10-03 10:41 UTC, LukasKorba commented on Tests/TestUtils/FakeService.swift
> +//    }
thx for good catch

2022-10-03 10:41 UTC, LukasKorba commented on Tests/TestUtils/FakeService.swift
> +//    }
thx again

2022-10-03 17:49 UTC, pacu approved these changes

2022-10-03 23:05 UTC, merged