[#523] Make a CompactBlockProcessor an Actor
zcash/ZcashLightClientKit pull request #565
Opened 2022-10-12 09:34 UTC by LukasKorba

Closes #523 

- Sample app refactored for the processor being an actor
- tests refactored as well
- dark side tests fixed
- code cleanup
- review of the code and last touches

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-10-12 17:34 UTC, Chlup requested changes

2022-10-12 17:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        let oldValue = state
This code is fine as it is. 

I only have a suggestion. What if we drop this method and call `transitionState(from: oldValue, to: newState)` from state gettter/and setter?

Something like:
```
public internal(set) var state: State = .stopped {
    didSet { transitionState(from: oldValue, to: newState) }
}
```

Feel free to ignore this suggestion. Maybe it's bad idea because we introduce kinda side effect.

2022-10-12 17:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +            let info = try await self.service.getInfo()
Are we ok with this no longer running on main thread?

2022-10-12 17:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        do {
Are we ok with this no longer run on main thread?

2022-10-12 17:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/NotificationCenterDefault.swift
> +struct NotificationCenterDefault {
Maybe we could do extension of `NotificationCenter` instead of introducing new struct. And we could call new methods `postOnMainThread(....` and `postNotificationOnMainThread(.....` to be super explicit about what is going. Now it's not clear in code on first sight what is going on. But this more about naming and code style. This code works fine.

2022-10-12 17:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                await NotificationCenterDefault.post(
I ma little bit lost here. `NotificationCenterDefault.post` isn't async method. So how `await` can be used here?

2022-10-12 17:34 UTC, Chlup commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +        try await withCheckedThrowingContinuation { continuation in
Can you please describe a bit why `withCheckedThrowingContinuation` must be used? I don't mean in the code. I mean here in the comment. I am not exactly sure what is going on here and I would like to understand it. Thanks.

2022-10-12 17:34 UTC, Chlup commented on Tests/TestUtils/TestCoordinator.swift
> +        Task {
I am thinking about this change. Previously code was executed synchronously. So first stop was called and then variables were set to nil. Now probably `stop` method exists earlier than `synchronizer.stop()` is called. Are we ok with this?

2022-10-13 02:47 UTC, pacu requested changes

2022-10-13 02:47 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        do {
I think we are as long as the tests pass

2022-10-13 02:47 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/NotificationCenterDefault.swift
> +struct NotificationCenterDefault {
I agree with this code being and extension with more explicit naming

2022-10-13 02:47 UTC, pacu commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +        try await withCheckedThrowingContinuation { continuation in
This uses a continuation that belongs to this task. If you just await this the XCWait won't work because the expectation will be waited for in a different context

2022-10-13 02:47 UTC, pacu commented on Tests/TestUtils/TestCoordinator.swift
> +        Task {
this should immediately stop everything

2022-10-13 11:10 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
> +    public func compactBlockStreamDownload(
good catch, back to internal

2022-10-13 11:18 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +            let info = try await self.service.getInfo()
The method is not used anywhere in the SDK or wallet. ideally remove it but after talk with android team I decided to leave it there as is - they claimed maybe some devs are using method we don't. Anyway, the API changed as well co I removed the completion block and left the method available.
```swift
func validateServer() async { ...
```

2022-10-13 11:20 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        do {
I asked myself the same and spent a lot of time testing it. I think nothing is dependent on main thread unless it touches UI. That is triggered by notifications only which we deliver on main thread now. So after testing and these facts I believe we are safe.

2022-10-13 11:29 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                await NotificationCenterDefault.post(
The await is actually for the 
```swift
self.getTransparentBalance()
``` 
inside the post. I put the await right before the call and removed @MainActor as we explicitly handle main thread inside of the post.

2022-10-13 11:46 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public func start(retry: Bool = false) async throws {
Not possible in this case as the start method is touching so many isolated properties.

```
All methods and mutable properties inside an actor are isolated to that actor by default, which means they cannot be accessed directly from code that’s external to the actor. Access to constant properties is automatically allowed because they are inherently safe from race conditions, but if you want you can make some methods excepted by using the nonisolated keyword.

Actor methods that are non-isolated can access other non-isolated state, such as constant properties or other methods that are marked non-isolated. However, they cannot directly access isolated state like an isolated actor method would; they need to use await instead.
```

2022-10-13 13:47 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        let oldValue = state
All recent changes of state handling were only because we needed thread safe solution and processor wasn't an actor.  The code before any async refactor for the state was 
```swift
public private(set) var state: State = .stopped {
        didSet {
            transitionState(from: oldValue, to: self.state)
        }
    }
```

and we can revert back to it thx to the Actor refactor.

2022-10-17 14:01 UTC, Chlup approved these changes

2022-10-20 14:47 UTC, pacu requested changes
Good work! Left some questions about how clients would use the API

2022-10-20 14:47 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/FigureNextBatch.swift
> +public extension CompactBlockProcessor {
Why is this needed to be public?

2022-10-20 14:47 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    public func start(retry: Bool = false) async throws {
I have a couple of questions about implementation on the client side.
How would a wallet use this API? 
What happens if the Task context that calls start() is cancelled? will the Synchronizer stop all the tasks in-flight?

2022-10-24 11:23 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/FigureNextBatch.swift
> +public extension CompactBlockProcessor {
removed

2022-10-25 12:43 UTC, LukasKorba commented on Tests/DarksideTests/SynchronizerTests.swift
> +        await self.coordinator.synchronizer.stop()
solved

2022-10-25 12:44 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    public func start(retry: Bool = false) async throws {
Synchronizer changed to have start and stop without async context

2022-10-25 17:00 UTC, pacu requested changes
I think there are some changes that weren't pushed because synchronizer protocol still has start and stop async

2022-10-25 17:00 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func start(retry: Bool) async throws
This doesn't match the implementation. 🧐

2022-10-25 17:00 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func stop() async throws
Same as above

2022-10-26 12:23 UTC, Chlup requested changes

2022-10-26 12:23 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static var birthdayHeight: BlockHeight = 2_000_000//ZcashSDK.isMainnet ? 935000 : 1386000
We probably don't want to merge these changes.

2022-10-26 12:37 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func start(retry: Bool) async throws
good catch, fixed (wonder why compiler is ok, no warnings, no nothing :()

2022-10-26 12:37 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func stop() async throws
good catch, fixed (wonder why compiler is ok, no warnings, no nothing :()

2022-10-26 12:37 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static var birthdayHeight: BlockHeight = 2_000_000//ZcashSDK.isMainnet ? 935000 : 1386000
reverted

2022-10-26 12:44 UTC, Chlup approved these changes

2022-10-26 18:04 UTC, pacu approved these changes
Approved with non blocking comments.

2022-10-26 18:04 UTC, pacu commented on Tests/TestUtils/TestCoordinator.swift
> +extension CompactBlockProcessor {
[non-blocking] I don't understand this change.

2022-10-27 10:44 UTC, LukasKorba commented on Tests/TestUtils/TestCoordinator.swift
> +extension CompactBlockProcessor {
The TestCoordinator modifies the processor's `config` but processor is actor-isolated context and write can't be done directly. You can read the value by awaiting it but can't modify it.

```swift
let c = await processor.config // is ok
await processor.config = newConfig // won't compile and honestly the syntax even doesn't make sense
await processor.modifyConfig(newConfig) // is ok
```

2022-10-27 10:46 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
> +        Task { @MainActor in
I personally never found a use case for MainActor.run API. Here it just throws 
```
Cannot pass function of type '@Sendable () async throws -> ()' to parameter expecting synchronous function type
```
What we need is to spin up the task to update the UI and this syntax does exactly that.

2022-10-27 10:51 UTC, merged