[#566] Parallel block processing
zcash/ZcashLightClientKit pull request #583
Opened 2022-10-27 17:13 UTC by Chlup

- Implements parallel downloading, validating and scanning of blocks.
- For now code makes sure that scanning is made in order. There is no support for full parallelisation in rust API yet.
- For now block processor downloads 100 blocks and then validate them and scanned them. Thanks to this not a lof of disk space is required for synchronisation.
- Most of the work is done in `CompactBlockProcessor.processNewBlocks(...)`.
- Progress reporting of `CompactBlockProcessor` is update so it works with new approach.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-10-27 23:18 UTC, pacu requested changes
Great work folks! left some comments, and questions too!

2022-10-27 23:18 UTC, pacu commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +
Tests that you should check that run:

- [ ] AdvancedReOrgTests
- [ ] BlockDownloaderTests
- [ ] DarksideSanityCheckTests
- [ ] PendingTransactionUpdatesTest
- [ ] ReOrgTests

2022-10-27 23:18 UTC, pacu requested changes
Great work folks! left some comments, and questions too!


Note: we are missing a changelog for all we are doing

2022-10-27 23:20 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                        while await parallelHandler.taskPool >= tasksInParallel {
According to this documentation https://developer.apple.com/documentation/swift/withthrowingtaskgroup(of:returning:body:)
I'm not sure if tasks will be cancelling the way we think they would

2022-10-28 08:03 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                let steps = wholeRange / downloadBatchSize
Solved when assigning value to `Config.downloadBatchSize`

2022-10-28 08:07 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/FigureNextBatch.swift
> +public extension CompactBlockProcessor {
Removed. Either we forgot to remove it after some experiment or it's a result of mistake in rebase.

2022-10-28 08:16 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        print("CANCELING TASK |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||")
Removed unnecessary log.

2022-10-28 08:16 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        print("_PARALLEL processNewBlocks STARTED ------------------------------------------------------ \(range) \(startTime)")
Removed unnecessary log.

2022-10-28 10:21 UTC, Chlup commented on Tests/DarksideTests/AdvancedReOrgTests.swift
> +
All the tests are passing for me. Except `BlockDownloaderTests.testSmallDownloadAsync`. And I fixed that one in https://github.com/zcash/ZcashLightClientKit/pull/594.

2022-10-28 10:54 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
>              for try await zcashCompactBlock in stream {
The previous code was ensuring only a few blocks are stored in memory by storing it to disc and remove from memory. Now the parallel solution handles it on a higher level so this function is no longer in charge of it. We run only a controlled amount of downloads (tasks) and clean up the cache from memory in processNewBlocks.

2022-10-28 10:55 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
> -                notifyProgress(
The new progress reporting is no longer split across operations (scan, download, enhance, ..). It's called syncing(progress) and merges all operations into one. The call of notifyProgress() is at a higher level in processNewBlocks

2022-10-28 10:59 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    case customValue(Float)
Fetching UTXOs is not divided into steps, even previous code wasn't reporting progress when fetching UTXOs. It just starts and waits when done. New progress reporting reserved 2% (98-100) for the fetching utxos. So when this done, we call notifyProgress() with custom value of 1 (exactly 100%). Meaning all work is done, synced state. It can also be used for the testing purposes. While the first two enums are specific for the progresses for related operations.

2022-10-28 11:02 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                        while await parallelHandler.taskPool >= tasksInParallel {
```
You can cancel a task group and all of its child tasks by calling the cancellAll() method on the task group, or by canceling the task in which the group is running.
```

The 2nd case is exactly our case. Why do you think withThrowingTaskGroup won't participate in cancelation?

2022-10-28 12:05 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                        while await parallelHandler.taskPool >= tasksInParallel {
Ok. Great. I thought it probably was the 2nd case but the doc is not well described and that iteration over the groups seem counter-intuitive.

2022-10-28 12:09 UTC, pacu requested changes
let's document the progress public API so people knows what we mean there. 

Also, let's start creating a changelog for public APIs changed. 

Great work!

2022-10-28 12:09 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    case customValue(Float)
Ok, since this is public it should be documented.

2022-11-01 18:36 UTC, pacu approved these changes

2022-11-01 19:41 UTC, LukasKorba approved these changes
LGTM

2022-11-02 17:32 UTC, pacu commented
It seems there are some compiler errors :/

2022-11-02 17:33 UTC, merged