Use only one stream when processing blocks in parallel
zcash/ZcashLightClientKit pull request #604
Opened 2022-11-03 09:29 UTC by Chlup

- It makes sense to have only one downloading stream for blocks even when processing blocks in parallel. Especially on mobile devices we can expect that internet connection won't be super fast.
- And it makes sense to not rely on some magic inside gRPC library and be sure that there always be only one download stream no matter what.
- Disadvantage of this approach is that there is no real parallelisation until we can scan in parallel. With this one stream approach we have multiple tasks but only one runs at the time.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-11-03 16:00 UTC, LukasKorba approved these changes
LGTM, haven't tested

2022-11-03 16:15 UTC, pacu requested changes

2022-11-03 16:15 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                                let buffer = try await readBlocks(from: downloadStream, at: processRange)
What is the size of this `processRange` in reality?

The approach seems a bit unclear, what's the amount of blocks that would be in flight? Consider that since height 1_600_000 blocks are almost full and take considerable space in memory and batches should be quite small.

2022-11-04 09:25 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                                let buffer = try await readBlocks(from: downloadStream, at: processRange)
It is always `config.downloadBatchSize`. Currently it's set to 100 blocks. We can set it to whatever we want (and whatever is acceptable for rust API).

2022-11-04 21:15 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                                let buffer = try await readBlocks(from: downloadStream, at: processRange)
I had to create that workaround for heights higher that 1_600_000 on mainnet because of blocksize. :/

2022-11-04 21:17 UTC, pacu requested changes
Let's incorporate that workaround for full blocks on mainnet as we have currently on the SDK

2022-11-07 10:23 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                                let buffer = try await readBlocks(from: downloadStream, at: processRange)
Ok. That makes sense. This PR doesn't change how many blocks is processed at ona batch. It's same as before. In this PR blocks are just read from from stream instead of lot of streams. I suggest to merge this PR now and then iterate on it and incorporate that workaround in next PRs.

2022-11-08 19:49 UTC, pacu requested changes
this looks good.

some minor comments we need to address

2022-11-08 19:49 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +
extra line not needed

2022-11-08 19:49 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +        if range.lowerBound > 1_600_000 {
signal that this has its correspoding FIXME  with issue https://github.com/zcash/ZcashLightClientKit/issues/576

2022-11-09 17:51 UTC, pacu approved these changes

2022-11-14 08:32 UTC, merged