[#613] Add support for background task to sample app
zcash/ZcashLightClientKit pull request #626
Opened 2022-11-15 13:18 UTC by Chlup

- `SyncBlocksViewController` now uses shared synchronizer instead of locally created block processor.
- When app goes to background background task is created so SDK has time to stop the work.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-11-15 15:30 UTC, pacu requested changes
I think this does not close #613, just one of its items.

2022-11-15 15:30 UTC, pacu commented on Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
> +                try synchronizer.start(retry: false)
I think we can remove the Task enclosing now that the await is gone

2022-11-15 15:30 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Call this wehn application will enter foreground.
```suggestion
    /// Call this when application will enter foreground.
```

2022-11-15 15:30 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///   - backgroundWorkFinished: Closure is called when synchronizer finishes stop of the work.
```suggestion
    ///   - backgroundWorkFinished: Closure is called when synchronizer finally stops
```

2022-11-15 15:30 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func applicationDidEnterBackground(resumeSyncWhenAppGoesToForeground: Bool, backgroundWorkFinished: @escaping () -> Void)
```suggestion
    func applicationDidEnterBackground(resumeOnForeground: Bool, synchronizerStopped: @escaping () -> Void)
```

I think these names are more concise. Also stopped doesn't imply that synchronizer finished syncing, it just refers to it stopping.

2022-11-15 15:30 UTC, pacu commented on Tests/TestUtils/TestCoordinator.swift
> +        if case .seedRequired = try synchronizer.prepare(with: seed) {
let's remove the `async` from line 294 since this function no longer requires being called on an async context

2022-11-15 15:30 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func applicationWillEnterForeground() throws
I don't think this needs to be part to the `protocol` since it's iOS dependent.

2022-11-16 09:44 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
> +                loggerProxy.error("Failed to start synchronisation after comming to foreground. \(error)")
Fixed

2022-11-16 09:55 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
> +    func startBackgroundWork() {
About "Maybe creating some helper class that SDK clients can use directly to spin up the tasks":
   I am not sure about this. Management of background task is one call which creates it. And then another call which invalidates it. It's super simple. I can create a helper which wraps these two calls but I don't see a point in that. There will still be two calls on app side. I don't see a reasonable way how could we simplify this.

About that documentation:
  What is your idea that should be in this documentation? In my code I start background task only to get time to stop synchronizer. So I can write suggestion that this background task should be used only to stop synchronizer. Basically only to use `applicationDidEnterBackground`. Where this documentation should be?

2022-11-16 09:56 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Call this wehn application will enter foreground.
Fixed

2022-11-16 09:58 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func applicationDidEnterBackground(resumeSyncWhenAppGoesToForeground: Bool, backgroundWorkFinished: @escaping () -> Void)
Fixed

2022-11-16 10:00 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func applicationWillEnterForeground() throws
If the app uses `Synchronizer` protocol instead of `SDKSynchronizer` type then this feature won't be available. And if we require developers to use `SDKSynchronizer` type then what is the purpose of `Synchronizer` protocol?

2022-11-16 15:47 UTC, pacu commented on Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
> +    func startBackgroundWork() {
> About "Maybe creating some helper class that SDK clients can use directly to spin up the tasks":
I am not sure about this. Management of background task is one call which creates it. And then another call which invalidates it. It's super simple. I can create a helper which wraps these two calls but I don't see a point in that. There will still be two calls on app side. I don't see a reasonable way how could we simplify this.

I trust your expertise and judgement on this. 

> Where this documentation should be?
we place dedicated docs con `/docs` and refer to it in the main README.md as something worth checking out.
Also add a CHANGELOG.md entry about these changes.

> What is your idea that should be in this documentation? 
I think we need to provide guidance on:
- how to handle the scenario of user backgrounding the app and what the app should do about the SDKSynchronizer
- how to handle the scenario of the user returning to the app and what it should do about the SDKSynchronizer.
- How to create long processing tasks that allow iOS to wake up the client app to sync blocks and what are the ideal conditions when that must happen (e.g.: device connected to power and Wi-Fi)
- How to create app refreshes for scanning some bit of blocks (when the app has caught up with latest blocks and would benefit from such app refreshes)

We should support this scenarios with code samples. (these could be either in the Demo app or ECC Wallet, whatever you think it is more content rich and fruitful)

2022-11-16 16:08 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func applicationWillEnterForeground() throws
Its original purpose was to be a OS-Agnostic interface that could host many implementations but we never got to that.  :(

2022-11-16 16:09 UTC, pacu requested changes
Answered comments! 👍

2022-11-17 12:42 UTC, pacu requested changes

2023-02-03 09:25 UTC, Chlup commented
Let's put this on side bench for now. We can reopen it when we get back to it.

2023-02-03 09:25 UTC, closed without merging