[#646] SDK sync process resumes correctly
zcash/ZcashLightClientKit pull request #648
Opened 2022-11-23 18:14 UTC by Chlup

- Previously we had one range for each sync which was used for each phase of sync process. Newly there is separate range for each phase of the sync process.
- I added `InternalSyncProgress` utility. This utility tracks progress of some phases. And it is able to compute right ranges which should be used for syncing.
- Some unused download code from `CompactBlockProcessor` is removed.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-11-28 08:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +//  File.swift
Pls name the file (when we have the header it should be at least meaningful)

2022-11-28 08:26 UTC, LukasKorba commented on Tests/TestUtils/InternalSyncProgressMemoryStorage.swift
> +//  File.swift
Her as well, renamer File.swift

2022-11-28 08:27 UTC, LukasKorba approved these changes
LGTM but haven't tested, the whole topic is pretty complex and I take it as workaround before we introduce some proper solution (state machine?).

2022-11-28 11:52 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +//  File.swift
This bug in Xcode is incredible.

2022-11-28 17:10 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +        case higherValue
I think this is a debug / log worthy situation.

```suggestion
        case wait(latestScannedHeight: BlockHeight, latestBlockHeight: BlockHeight)
```

2022-11-28 17:11 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +    ///   - latestBlockHeight: Latest height fetched from backend API.
```suggestion
    ///   - latestBlockHeight: Latest height fetched from LightWalletd API.
```

2022-11-28 17:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +    func typeOfWorkRemaining(latestBlockHeight: BlockHeight, latestDownloadedHeight: BlockHeight, latestScannedHeight: BlockHeight) -> TypeOfWork {
I don't see any particular tests of this function that has many OR sentences and can be tricky. 
I also think it could have better documentation of the intent so that any further changes to it can be checked against the documentation and verify that the logic we intend to have here still holds

2022-11-28 17:18 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +    ) -> SyncRanges {
we should add docs about what this computation is and what the returned values mean.

2022-11-28 17:33 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +                    await internalSyncProgress.set(utxo.height, .latestUTXOFetchedHeight)
I think the `computeSyncRanges` and `typeOfWorkRemaining` might make assumptions that are incorrect because of how "fetch" works. 

we fetch and `upsert` every UTXO available for the addresses that the user has derived and given out for receiving transparent funds. There's caveat here. If the user doesn't shield its funds, this code will always receive the same UTXOs. These will eventually get "old" and reflect a height that's far away from the chain tip. 

Does a `utxo.height` that is far from the latest mined block mean that the wallet is not synced? Absolutely not. It's just that the wallet hasn't bothered to shield those funds. 

There are re-org considerations as well. Line 73 below shows that the `range.upperbound` is saved as `latestUTXOFetchedHeight`. What are we keeping this partial result on line 58 for?

If there's a re-org that removes UTXOs from blocks we might not be capturing that because we are storing a `latestUTXOFetchedHeight` of a UTXO that does not exist anymore or that it might appear on a later block.

How does `internalSyncProgress` handle re-orgs?

2022-11-29 09:31 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +//  File.swift
Renamed

2022-11-30 10:39 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +        case higherValue
I changed a code a this enum is now gone.

2022-11-30 11:21 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
> +    func typeOfWorkRemaining(latestBlockHeight: BlockHeight, latestDownloadedHeight: BlockHeight, latestScannedHeight: BlockHeight) -> TypeOfWork {
I updated the documentation and added tests for InternalSyncProgress.

2022-11-30 11:30 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +                    await internalSyncProgress.set(utxo.height, .latestUTXOFetchedHeight)
> I think the `computeSyncRanges` and `typeOfWorkRemaining` might make assumptions that are incorrect because of how "fetch" works.
> 
> we fetch and `upsert` every UTXO available for the addresses that the user has derived and given out for receiving transparent funds. There's caveat here. If the user doesn't shield its funds, this code will always receive the same UTXOs. These will eventually get "old" and reflect a height that's far away from the chain tip.
> 
> Does a `utxo.height` that is far from the latest mined block mean that the wallet is not synced? Absolutely not. It's just that the wallet hasn't bothered to shield those funds.

I am not sure if I understand this. My thinking was that if we fetch UTXO for some height then we are done for this height. And no new UTXOs can be find at that height. So it's enough to fetch UTXO for that height just once.

> 
> There are re-org considerations as well. Line 73 below shows that the `range.upperbound` is saved as `latestUTXOFetchedHeight`. What are we keeping this partial result on line 58 for?

Because exception can be thrown during processing of each UTXO. And that latest processed height wouldn't be stored. It can work without that. SDK just fetches already fetch UTXOs on next sync.

> 
> If there's a re-org that removes UTXOs from blocks we might not be capturing that because we are storing a `latestUTXOFetchedHeight` of a UTXO that does not exist anymore or that it might appear on a later block.
> 
> How does `internalSyncProgress` handle re-orgs?

`InternalSyncProgess` has `rewind()` method. It is called in `validationFailed()`.

2022-11-30 11:34 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
@pacu Could you please check this? Previously we had one range so it was super easy to have range which is passed to `processBatchFinished()` method. But now we have multiple ranges. I think that I did right think but may I overlooked something.

2022-11-30 15:40 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +                    await internalSyncProgress.set(utxo.height, .latestUTXOFetchedHeight)
Thanks for the response. I'll take a look at `validationFailed` and `rewind` !

2022-11-30 18:31 UTC, pacu requested changes
I responded the questions. I think this is good progress

2022-11-30 18:31 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
>          try downloader.rewind(to: BlockHeight(rewindHeight))
```suggestion
        let rewindHeight = BlockHeight(rewindHeight)
        try downloader.rewind(to: rewindHeight)
        await internalSyncProgress.rewind(to: rewindHeight)

        self.lastChainValidationFailure = nil
        self.lowerBoundHeight = try? downloader.lastDownloadedBlockHeight()
        return rewindHeight
```

2022-11-30 18:31 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
uhhmm it seem so but how do you think the processor should react when this guard statement is negative?


````Swift
  internal func processBatchFinished(range: CompactBlockRange) async {
        guard processingError == nil else {
            await retryProcessing(range: range)
            return
        }
````

2022-11-30 18:31 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
shall we pass  syncRanges instead?

2022-11-30 18:35 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
> +                    await internalSyncProgress.set(utxo.height, .latestUTXOFetchedHeight)
I think this is doing the right thing but I'll try to test it as well

2022-12-01 10:03 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
Problem of SyncRanges is that ranges inside are optionals. `nil` instead of range means that we don't want to do specific phase. For example when everything is already downloaded then range for download is `nil`. And what should be passed when all are for example `nil`? Which range should be used?

2022-12-02 11:57 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
do we have a copy of the original `SyncRanges` at this point in the code? I think the main problem is that we originally coded a function that says "Finished! .... oh no wait.. there's an error" because of how NSOperations fail asynchronously and cancel lazily and unreliable. Now that we don't use them, I believe we can split the `finished` from  the `failed` and this dilemma will be resolved.

2022-12-02 11:58 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
If we do have a copy of the original range we failed at, we could patch this by adding that to the parameters passed and the retry would pass that to start over. Otherwise probably refactoring this is for the better

2022-12-02 11:58 UTC, pacu requested changes
@Chlup sorry for the delay. I think I might thought of a path forward to the processingFinished dilemma. Please let me know your thoughts

2022-12-05 10:14 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
I tried to change this. And then I realised. I don't think that `retryProcessing()` is ever called. It is called from `processBatchFinished()` only when `processingError` is not `nil`. `processingError` is set only in `serverFailure()` and `fail()` methods. But none of these two methods is called inside sync process. 

What do you think about this? Did I miss something? 

I am thinking about how to approach this. Either we say it's ok and remove it. Or we say it is a bug and it must be fixed. But it may mean some kind of error tracking overhaul.

2022-12-05 21:36 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
> I tried to change this. And then I realised. I don't think that retryProcessing() is ever called. It is called from processBatchFinished() only when processingError is not nil. processingError is set only in serverFailure() and fail() methods. But none of these two methods is called inside sync process.

I think this might be the case since we moved away from NSOperations now task that fail throw errors instead of reporting them lazily. My take is that it might be safe to remove it.

2022-12-05 21:42 UTC, pacu commented
I tested this using `master` of ECC Wallet. And found a bug.

When you do a quick re-scan (profile -> Rescan Wallet -> Quick Re-scan) the wallet shows no balance and the SDK reports being synced without rescanning

````
2022-12-05 18:38:45.388734-0300 ECC-Wallet-Testnet[8507:260681] [] InternalSyncProgress[86] - computeNextState(latestBlockHeight:latestDownloadedBlockHeight:latestScannedHeight:walletBirthday:) - DEBUG 🐞 - Init numbers:
latestDownloadedHeight:  2116088
latestScannedHeight:     2116089
latestEnhancedHeight:    0
latestUTXOFetchedHeight: 0
````


I think it's because the scanned height should be updated to the latestScannedheight that results of rewinding.

2022-12-05 21:45 UTC, pacu requested changes
See comments on ECC Wallet tests

2022-12-06 09:00 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +                    await processBatchFinished(range: lastScannedHeightBeforeSync...lastScannedHeightAfterSync)
Ok. Code removed. Thanks for advice.

2022-12-08 11:43 UTC, Chlup commented
> I tested this using `master` of ECC Wallet. And found a bug.
> 
> When you do a quick re-scan (profile -> Rescan Wallet -> Quick Re-scan) the wallet shows no balance and the SDK reports being synced without rescanning
> 
> ```
> 2022-12-05 18:38:45.388734-0300 ECC-Wallet-Testnet[8507:260681] [] InternalSyncProgress[86] - computeNextState(latestBlockHeight:latestDownloadedBlockHeight:latestScannedHeight:walletBirthday:) - DEBUG 🐞 - Init numbers:
> latestDownloadedHeight:  2116088
> latestScannedHeight:     2116089
> latestEnhancedHeight:    0
> latestUTXOFetchedHeight: 0
> ```
> 
> I think it's because the scanned height should be updated to the latestScannedheight that results of rewinding.

@pacu This is because `latestScannedHeight` is taken from `TransactionRepository` and that doesn't support rewinding. I suggest to handle this as separate issue. It's not regression of this change and it was happening before. I wouldn't like to make this PR even bigger. I can create ticket and try to solve it separately. Is that Ok with you?

2022-12-08 11:45 UTC, Chlup commented
@pacu So I did some changes. Now #660 is fixed in this code. Latest downloaded block is no longer tracked by using cache DB but it's tracked in `InternalSyncProgress`. Thanks to this cache DB can be completely removed after sync. I did some testing and it seems fine to me. Please check it out.

2022-12-10 18:18 UTC, pacu requested changes
I tested the changes on ECC Wallet Testnet, was able to quick re-scan as I wasn't able to.

Most of the darksidewalletd tests passed, except for `TransactionEnhancementTests` which never gets to finish. This might be giving us some interesting caveat we are not catching. 

````
2022-12-10 15:16:22.564835-0300 xctest[8175:67599] [INFO ℹ️] CompactBlockProcessor.swift - nextBatch() - Line: 790 -> Lightwalletd might be syncing: latest downloaded block height is: 687059 while latest blockheight is reported at: 663200
```

2022-12-12 13:28 UTC, pacu approved these changes
<img width="412" alt="image" src="https://user-images.githubusercontent.com/484008/207056710-21c9161c-700c-4b5f-9252-19d8b623813a.png">
All tests pass.

2022-12-12 13:49 UTC, merged