[#637] Make sapling parameter download part of processing blocks
zcash/ZcashLightClientKit pull request #650
Opened 2022-11-24 09:20 UTC by LukasKorba

Closes #637 

- sync process enhanced to try to download sapling params if needed
- tests fixed

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-11-24 11:16 UTC, Chlup approved these changes
For me everything looks good. But it would be great if @pacu takes a look also.

2022-11-28 13:17 UTC, pacu requested changes

2022-11-28 13:17 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public func getBalance(accountIndex: Int) throws -> WalletBalance {
Why are we adding this public function?

2022-11-28 13:17 UTC, pacu commented on Sources/ZcashLightClientKit/Providers/ResourceProvider.swift
> +        URL(fileURLWithPath: "file://\(ZcashSDK.cloudParameterURL + ZcashSDK.spendParamFilename)")
I don't think this is the URL you are looking for

````Swift
    /// The Url that is used by default in zcashd.
    /// We'll want to make this externally configurable, rather than baking it into the SDK but
    /// this will do for now, since we're using a cloudfront URL that already redirects.
    public static var cloudParameterURL = "https://z.cash/downloads/"
````

2022-11-28 13:58 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
> +    public func getBalance(accountIndex: Int) throws -> WalletBalance {
I got rid of the whole function and simplified it since it's living only at one place where it's internally needed.

2022-11-28 14:05 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Providers/ResourceProvider.swift
> +        URL(fileURLWithPath: "file://\(ZcashSDK.cloudParameterURL + ZcashSDK.spendParamFilename)")
Weird, maybe some copy paste issue, good catch. Fixed

2022-11-28 16:46 UTC, pacu approved these changes

2022-11-28 16:46 UTC, pacu commented
I think this needs rebasing

2022-11-29 06:38 UTC, merged