[#556] Define structures for db view and add new repository methods
zcash/ZcashLightClientKit pull request #674
Opened 2022-12-14 13:18 UTC by Chlup

- Structures that represent transactions DB views are newly define.
- New structures are:
  - TransactionNG.Overview
  - TransactionNG.Received
  - TransactionNG.Sent

- `TransactionNG` is used as temporary name. `Transaction` is existing structure in the code. `TransactionNG` will be eventually renamed to `Transaction` once current `Transaction` is removed from code.

- New methods that are using new structures are added to `TransactionRepository`. Those are slightly changed compared to predecessors. Those are now little bit simpler to use.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- x ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-12-14 19:44 UTC, pacu requested changes

2022-12-14 19:44 UTC, pacu commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +        guard let entity = entities.first else { throw TransactionRepositoryError.notFound }
Why would we consider an Error that a query returns no results? Wouldn't it be better to return an Optional<Entity>?

2022-12-14 19:52 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +        guard let entity = entities.first else { throw TransactionRepositoryError.notFound }
We could. It just seems to me like using two different technologies to report some exceptional state. It means that if you call this API you have to handle exception and Optional. But there is not hard technical reason why to do this in this way. I just think that it will be easier to use in this way. If you think that we should use Optionals here no problem at all. I can change it.

2022-12-14 20:57 UTC, pacu approved these changes

2022-12-14 20:57 UTC, pacu commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +        guard let entity = entities.first else { throw TransactionRepositoryError.notFound }
Seems reasonable. let's leave it this way

2022-12-15 13:52 UTC, pacu approved these changes

2022-12-15 21:07 UTC, ccjernigan reviewed
I'm not as familiar with the iOS code base, but I do have a few comments/questions inline below.

2022-12-15 21:07 UTC, ccjernigan commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +        static let minedHeight = Expression<Int>("mined_height")
Heights are technically UInt32 in the Rust code, so we should probably make this Int64 in the Swift code and then convert to our BlockHeight typesafe object.

2022-12-15 21:07 UTC, ccjernigan commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .prepare(query)
I don't know enough about how you're internally maintaining the database connections.  Is the dbProvider maintaining a long-lived connection?

Would it make sense in this case to use something like `.lazy()` so that the entire table doesn't have to be queried at once?

2022-12-15 21:07 UTC, ccjernigan commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +                TransactionNG.Sent.Column.minedHeight >= Int(range.start.height) &&
Heights shouldn't be cast to Int for the comparison, since BlockHeight is UInt32.

2022-12-15 21:07 UTC, ccjernigan commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .order(TransactionNG.Overview.Column.minedHeight.asc, TransactionNG.Overview.Column.id.asc)
If we only expect to return a single item, does it make sense to include the `order()` call?

2022-12-15 21:14 UTC, Chlup commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +        static let minedHeight = Expression<Int>("mined_height")
In the iOS codebase we have `BlockHeight` data type which is just an alias to Int. Any device on which our code can currently run has 64bit CPU so both Int and Int64 can hold same values. I switched from `Int` to `BlockHeight` at height related rows so it's little bit more clear.

2022-12-15 21:16 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .prepare(query)
It has "lazy" behavior inside. Checkout `SimpleConnectionProvider` to see real implementation of how connection is created and provided.

2022-12-15 21:17 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +                TransactionNG.Sent.Column.minedHeight >= Int(range.start.height) &&
It's similar case as [above](https://github.com/zcash/ZcashLightClientKit/pull/674#discussion_r1050141458). I switched to `BlockHeight` from `Int` to be more clear.

2022-12-15 21:18 UTC, Chlup commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .order(TransactionNG.Overview.Column.minedHeight.asc, TransactionNG.Overview.Column.id.asc)
No it doesn't. Good catch.

2022-12-15 21:18 UTC, Chlup commented
@ccjernigan Thanks for the review!

2022-12-15 21:19 UTC, ccjernigan commented
> @ccjernigan Thanks for the review!

You're welcome!  I don't have any other questions—thanks for helping me understand the iOS codebase a bit better too 😄

2022-12-15 21:21 UTC, ccjernigan approved these changes

2022-12-16 12:33 UTC, merged