Implementation of Filesystem compact block repository
zcash/ZcashLightClientKit pull request #679
Opened 2022-12-16 00:56 UTC by pacu

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-01-25 12:42 UTC, Chlup requested changes
The code looks ok to me. I have few comments but mostly about changelog or documentation. Nice job.

I tested cases like this:
- Full sync with fs cache.
- Interrupted and resumed full sync with fs cache.
- Sync which was started with previous code (from main branch), interrupted and then finished with fs cache.

All seems to work. I found one detail which works now but may not work in future. 

I found it when testing case when sync was started without fs cache, interrupted and then resumed with fs cache.

Latest downloaded height is tracked in `InternalSyncProgress`. It may happen that blocks are  downloaded and sync process is interrupted. When sync process is started again `InternalSyncProgress` assumes that there are some downloaded blocks which are not scanned. But there aren't any because cacheDB is removed on the app start. And we ask rust backend to scan blocks which are not there. It looks like that it works now and rust doesn't throw any error. But it may throw error in future. Maybe `latestDownloadedBlockHeight` in `InternalSyncProgress` should be set to latest scanned block.

2023-01-25 12:42 UTC, Chlup commented on MIGRATING.md
> +information from one cache to another, would possibly fail
Dot is missing at the end of the last sentence in paragraph.

2023-01-25 14:09 UTC, pacu commented on Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
> +            try initializer.migrateCacheDb(try cacheDbURLHelper())
The main problem is that we require the user to send us a path to a sqlite file, and this uses a directory instead.

We could assume that the directory has the same read-write permissions than the file itself and perform `cacheDbURL.removingLastPathComponent()` and use that directory for fsBlockDbRoot but it doesn't seem elegant either.

The real change we are missing is using an SDKSynchronizer coordinator of some sort that manages aliases and instances of different synchronizers and the whereabout of the files. but it's out of scope for this PR :/

2023-01-25 14:19 UTC, pacu commented on CHANGELOG.md
> +### Added
Thanks! that was a rebase burp

2023-01-26 08:45 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
> +            try initializer.migrateCacheDb(try cacheDbURLHelper())
Now I understand the motivation. Thanks for explanation. 

What if we keep `cacheDbURL` parameter in `Initializer.init`? Applications will be forced to gives this URL to SDK. But that's all for them. Then the SDK can handle migration of cache DB on it's own.

2023-01-26 23:01 UTC, pacu commented
> The code looks ok to me. I have few comments but mostly about changelog or documentation. Nice job.
> 
> I tested cases like this:
> 
> * Full sync with fs cache.
> * Interrupted and resumed full sync with fs cache.
> * Sync which was started with previous code (from main branch), interrupted and then finished with fs cache.
> 
> All seems to work. I found one detail which works now but may not work in future.
> 
> I found it when testing case when sync was started without fs cache, interrupted and then resumed with fs cache.
> 
> Latest downloaded height is tracked in `InternalSyncProgress`. It may happen that blocks are downloaded and sync process is interrupted. When sync process is started again `InternalSyncProgress` assumes that there are some downloaded blocks which are not scanned. But there aren't any because cacheDB is removed on the app start. And we ask rust backend to scan blocks which are not there. It looks like that it works now and rust doesn't throw any error. But it may throw error in future. Maybe `latestDownloadedBlockHeight` in `InternalSyncProgress` should be set to latest scanned block.

Thank you for pointing this out! I added an integration test that attempts to recreate such scenario in a more or less reproducible way in this commit `3a9d78963f26dd6832110a2fe6a0a12ca32e1348`

2023-01-27 11:24 UTC, Chlup requested changes
Nice job with tests.

2023-01-27 11:24 UTC, Chlup commented on Sources/ZcashLightClientKit/Initializer.swift
> +        userDefaults.setValue(
I totally understand the motivation for this but I think this will bite us eventually. [Here](https://github.com/zcash/ZcashLightClientKit/pull/679#discussion_r1087557327) I suggested to keep cacheBD param in Initializer constructor. If we do this then we can pass cacheDB URL to CompactBlockProcessor. And we can execute migration on sync start or any place in CBP. And almost everything CBP is async.

2023-01-31 13:25 UTC, Chlup approved these changes

2023-02-01 21:37 UTC, pacu commented
Tests passed 
```
Test Suite 'Zip302MemoTests' passed at 2023-02-01 18:29:34.260.
	 Executed 20 tests, with 0 failures (0 unexpected) in 0.022 (0.046) seconds
Test Suite 'OfflineTests.xctest' passed at 2023-02-01 18:29:34.260.
	 Executed 167 tests, with 0 failures (0 unexpected) in 15.378 (15.442) seconds
Test Suite 'All tests' passed at 2023-02-01 18:29:34.288.
	 Executed 167 tests, with 0 failures (0 unexpected) in 15.378 (15.471) seconds
Test Suite 'AdvancedReOrgTests' passed at 2023-02-01 18:35:50.000.
	 Executed 11 tests, with 0 failures (0 unexpected) in 276.848 (276.851) seconds
Test Suite 'DarksideTests.xctest' passed at 2023-02-01 18:35:50.001.
	 Executed 11 tests, with 0 failures (0 unexpected) in 276.848 (276.851) seconds
```

2023-02-02 16:58 UTC, merged