[#663] Create a benchmarking section on the Demo App that can be auto…
zcash/ZcashLightClientKit pull request #681
Opened 2022-12-19 11:25 UTC by LukasKorba

Closes #663 

- SDKMetrics singleton for the measurement
- download, validate and scan blocks supported
- Sample app refactored to use SDKMetrics, connected to appropriate notifications and labels
- enhancement metric added
- total sync time metric added
- sample app extended to show summary time and operations summaries
- SDKMetrics cleanup and logical separation
- unit tests for the SDKMetrics

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2022-12-19 11:43 UTC, Chlup requested changes

2022-12-19 11:43 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/Constants/Testnet.swift
> +let kZcashNetwork = ZcashNetworkBuilder.network(for: .mainnet)
This is changed on purpose or not?

2022-12-19 11:43 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static var seed = try! Mnemonic.deterministicSeedBytes(from: "wish puppy smile loan doll curve hole maze file ginger hair nose key relax knife witness cannon grab despair throw review deal slush
This is changed on purpose or not?

2022-12-19 11:43 UTC, Chlup commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +    static let live = Self(
SDK doesn't use "secant style" interfaces. Protocols are mostly used. I don't it matters much. In sake of consistency I would for simply protocol use instead of this approach. But this will work fine. So I keep the final decision what to do here to you.

2022-12-19 11:43 UTC, Chlup commented on Tests/NetworkTests/BlockScanTests.swift
> +//        guard let report = SDKMetrics.blockReportFromNotification(notification) else {
You probably want to remove commented code?

2022-12-19 11:49 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Constants/Testnet.swift
> +let kZcashNetwork = ZcashNetworkBuilder.network(for: .mainnet)
mistake, good catch

2022-12-19 11:49 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static var seed = try! Mnemonic.deterministicSeedBytes(from: "wish puppy smile loan doll curve hole maze file ginger hair nose key relax knife witness cannon grab despair throw review deal slush
mistake, good catch

2022-12-19 12:12 UTC, LukasKorba commented on Tests/NetworkTests/BlockScanTests.swift
> +//        guard let report = SDKMetrics.blockReportFromNotification(notification) else {
fixed

2022-12-19 12:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
> +    static let live = Self(
protocol it is

2022-12-19 14:32 UTC, pacu requested changes

2022-12-19 14:32 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +public class SDKMetrics {
SDK Metrics needs it's own entry on the `CHANGELOG.md` and also an explanation on how clients might use it under `docs/` .

2022-12-19 20:08 UTC, LukasKorba commented on Package.swift
> +        .package(url: "https://github.com/zcash-hackworks/MnemonicSwift", from: "2.1.0"),
resolved by hardcoding seedBytes from base64 string

2022-12-19 20:09 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
> +                progress: BlockProgress(startHeight: range.lowerBound, targetHeight: range.upperBound, progressHeight: range.upperBound),
resolved

2022-12-19 21:03 UTC, pacu approved these changes
untested ack. 

LGTM modulo this comment https://github.com/zcash/ZcashLightClientKit/pull/681/files#r1052230985

2022-12-20 10:22 UTC, Chlup approved these changes

2022-12-20 18:42 UTC, pacu requested changes
I've review the Documentation and caught a typo on the API that spread across the whole PR. Seems a lot but it can probably be fixed by a `replace all`

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +    /// `SDKMEtrics` focuses deeply on a sync process and metrics related to it. By default there are reports around
```suggestion
    /// `SDKMEtrics` focuses deeply on sync process and metrics related to it. By default there are reports around
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// The processing of data is either left on a user of `SDKMetrics` or anybody can take an advantage of extension APIs
```suggestion
/// The processing of data is either left to the user of `SDKMetrics` or anybody can take an advantage of extension APIs
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// The `SDKMetrics` has been designed so it has the lowest impact possible on the SDK itself.
```suggestion
/// The `SDKMetrics` API has been designed so it has the lowest impact possible on the SDK itself.
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// Reporting of the metrics is already in place but ignored till `enableMetrics()` is called. Once turned on, the data are collected
```suggestion
/// Reporting of the metrics is already in place but ignored untill `enableMetrics()` is called. Once turned on, the data is collected
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// and cummulated to the in memory structural storage untill `disableMetrics()` is called.
```suggestion
/// and cumulated to the in-memory structural storage until `disableMetrics()` is called.
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// Get RAW data by calling either `popBlock` or `popAllBlockReports`. The post-processing of data is then on a caller.
```suggestion
/// Get RAW data by calling either `popBlock` or `popAllBlockReports`. The post-processing of data is then delegated to the caller.
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// Get cummulated data by using an extension APIs. For the summarized collection, call `cummulativeSummary()`.
```suggestion
/// Get cumulated data by using an extension APIs. For the summarized collection, call `cumulativeSummary()`.
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// Sometimes, typically when you want to run several iterations, the `cummulateReportsAndStartNewSet()` automatically computes
```suggestion
/// Sometimes, typically when you want to run several iterations, the `cumulateReportsAndStartNewSet()` automatically computes
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// cummulativeSummary, stores it and starts to collect a new set. All summaries can be either processed by a caller,
```suggestion
/// cumulativeSummary, stores it and starts to collect a new set. All summaries can be either processed by a caller,
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +/// accessing the collection `cummulativeSummaries` directly or values can be merged into one final summary by calling `summarizedCummulativeReports()`.
```suggestion
/// accessing the collection `cumulativeSummaries` directly or values can be merged into one final summary by calling `summarizedCumulativeReports()`.
```

2022-12-20 18:42 UTC, pacu commented on Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
> +    public var cummulativeSummaries: [CummulativeSummary] = []
```suggestion
    public var cumulativeSummaries: [CummulativeSummary] = []
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +Benchmarking the SDK is one of the key focuses of Zcash. The most important operation of the SDK is the ability to synchronize blocks in order to be able to see transactions, right balances and be ab
```suggestion
Benchmarking the SDK is one of the key focuses of `SDKMetrics` API. The most important operation of the SDK is the ability to synchronize blocks in order to see transactions, right balances and to send & receive funds. In short, be in sync with the blockchain. Synchronization consists of several sub-operations like downloading the blocks, validating & scanning, etc.
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +The initial work on benchmarking/performance testing allows us to properly measure times spend in sub-operations of a synchronization. There will be iterations and enhancements and ideally fully auto
```suggestion
The initial work on benchmarking/performance testing allows us to properly measure times spent in sub-operations of a synchronization. There will be iterations and enhancements and ideally fully automated solution one day but for now we rely on manual approach.
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +    case enhancement                // enhancement of the transactions
```suggestion
    case enhancement                   // enhancement of the transactions
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +`SDKMetrics` holds the reports in a dictionary where keys are the operations. You can receive the data via either of following methods.
```suggestion
`SDKMetrics` holds the reports in a dictionary where keys are the operations. You can receive the data via either of the following methods.
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +struct CummulativeSummary: Equatable {
```suggestion
struct CumulativeSummary: Equatable {
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +As you can see `CummulativeSummary` basically holds `min`, `max` and `avg` times per `Operation`. To generate such summary you call:
```suggestion
As you can see `CumulativeSummary` basically holds `min`, `max` and `avg` times per `Operation`. To generate such summary you call:
```

2022-12-20 18:42 UTC, pacu commented on docs/testing/Performance.md
> +We encourage you to visit `Tests/PerformanceTests/` folder and check especially `SynchronizerTests` where we do exactly what is mentioned in this doc. We run synchronization for specific range of 100
```suggestion
We encourage you to visit `Tests/PerformanceTests/` folder and check `SynchronizerTests` where we do exactly what is mentioned in this doc. We run synchronization for a specific range of 100 blocks 5 times, measure every run separately and merge results together in the end. The `SDKMetrics` and `SynchronizerTests` lay down foundations for the future automatization of performance testing.
```

2022-12-21 12:16 UTC, pacu approved these changes

2022-12-21 12:30 UTC, merged