[#743] Refactor blocks validation in CompactBlockProcessor
zcash/ZcashLightClientKit pull request #753
Opened 2023-02-01 12:00 UTC by Chlup

Closes #743

- Added new protocol `BlockValidator` and `BlockValidatorImpl` class. All the code related to blocks validation is extracted to `BlockValidatorImpl`.
- Fixed `testSingleDownloadAndScan()` test.
- Changed how validation error are handled. Previously validation error were handled directly next to validation code. And when some validation errors happened method from `CompactBlockProcessor` were called. Now validation errors are handled in `CompactBlockProcessor.processNewBlocks` in a same way as any other error that can occur during sync process.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-02-02 18:03 UTC, pacu requested changes

2023-02-02 18:03 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
> +struct BlockDownloaderImpl {
I'm pretty sure  `InternalSyncProgress` and `LightWalletService` are classes. Are we sure we want to make this a `struct`?

2023-02-02 18:03 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> -enum CompactBlockProcessorBuilder {
Is this not used any more? good catch!

2023-02-03 09:02 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        let blockValidatorConfig = BlockValidatorConfig(cacheDB: config.cacheDb, dataDB: config.dataDb, networkType: config.network.networkType)
It was my original approach. But it can't because it requires `config` which is one of params. And I can't access it from there. This is one of the reasons why I feel that we miss some kind of dependency injection. Now it's probably impossible to mock these internal dependencies of CBP.

2023-02-03 09:04 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        self.blockValidator = BlockValidatorImpl(config: blockValidatorConfig, rustBackend: backend)
This is probably personal preference. I don't like the syntax that you suggested. In my opinion it's harder to read. And harder to debug. If you would like to debug what is in instance `BlockValidatorConfig` it would be harder in this way in my opinion. 

But I leave this up to you. If you say that we prefer suggested syntax in this project I will change it.

2023-02-03 09:07 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
> +struct BlockDownloaderImpl {
I think we do. [Suggested approach by Apple](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes) is tu use structures by default. And use classes when you need them. I don't think that we need any class here. `BlockDownloaderImpl` doesn't keep any data. It has only dependencies. We don't care about copying (if some happens). There is no mutability. And use of class inside structure is absolutely fine. Structure is copied but classes inside are not.

2023-02-03 09:08 UTC, Chlup commented on Sources/ZcashLightClientKit/Initializer.swift
> -enum CompactBlockProcessorBuilder {
👍

2023-02-03 09:08 UTC, Chlup commented
@pacu I answered all your questions and rebase to main.

2023-02-03 14:36 UTC, pacu approved these changes

2023-02-03 14:52 UTC, merged