[#795] Include sapling-spend file into bundle for tests
zcash/ZcashLightClientKit pull request #798
Opened 2023-02-17 07:51 UTC by Chlup

Closes #795

- Added structure `SaplingParamsSourceURL` which holds source URLs for sapling-spend file and sapling-output file. URLs are ultimately passed to `SaplingParameterDownloader`.
- This is done so it's possible to pass different URLs when running tests.
- sapling-spend file and sapling-output file are in tests bundle. And when running tests these files are loaded from bundle and not from network.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-02-17 13:16 UTC, pacu requested changes

2023-02-17 13:16 UTC, pacu commented on CHANGELOG.md
> +    This is only an internal change and doesn't change the behavior of the SDK. `Initialier`'s
```suggestion
    This is only an internal change and doesn't change the behavior of the SDK. `Initializer`'s
```

2023-02-17 13:16 UTC, pacu commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        let saplingParamsSourceURL: SaplingParamsSourceURL
place constants before vars 🙏🙏🙏

2023-02-17 13:16 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +public struct SaplingParamsSourceURL {
Could you document what this is for and how it should be used?

2023-02-17 13:16 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +    let saplingParamsSourceURL: SaplingParamsSourceURL
please place constant before vars.

2023-02-20 10:17 UTC, LukasKorba approved these changes

2023-02-20 16:18 UTC, pacu approved these changes
UtACK!

2023-02-20 21:32 UTC, merged