[#801] Impro wipe implementation
zcash/ZcashLightClientKit pull request #802
Opened 2023-02-20 09:53 UTC by Chlup

Closes #801

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-02-21 12:03 UTC, pacu requested changes

2023-02-21 12:03 UTC, pacu commented on Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift
> +            case .wipe: hasher.combine(0)
Are all `.wipe` the same regardless their context? this is what this hasher seems to mean.

2023-02-21 13:17 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/ViewController.swift
> +            You are about to wipe existing wallet. You will lose all synced blocks, stored TXs, etc. If the sync is in progress it may take some \
Changed the text.

2023-02-21 13:20 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift
> +        if case let .wipe(wipeContext) = hooks.first(where: { $0 == Hook.emptyWipe }) {
I don't need to detect `emptyWipe`. I want to find any `wipe`. And I can't simply use `.wipe` because it has associated object. And because hooks are stored in Set and all the `wipe` have same hash there will be always only one `wipe`.

2023-02-21 13:24 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/ViewController.swift
> +            state. And it may not be able to handle this state. It's suggested to remove the app and install it again. Sorry.
We delete these four things: FS blocks cache, legacy cache DB, pending DB, data DB in this order. If removal of one item fails all the items that should be deleted after won't be deleted. Which may result in different states of inconsistency. I am not sure how to handle this better. 

Maybe I could mark that wipe started and remove this mark only when it finish successfully. And then when CBP starts and detects that there is a started wipe mark it can try to run wipe again. And if it fails it switch SDK state to `error`.

Or we can block start of the SDK until wipe finishes successfully. And it would be up to app to call the wipe until it succeed. 

But both are similar dead ends with just little hope added. When removal of file which exists fail then probably filesystem is broken and we can't do much.

Maybe you have some idea?

2023-02-21 13:32 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift
> +            case .wipe: hasher.combine(0)
Yes. That's how it's designed. It doesn't make sense to have multiple wipe hooks. Only one wipe can be executed. Now I realise that if somebody calls wipe multiple times then only latest publisher completes. Question is if we need to handle this or just to write that calling another wipe before previous finishes results in undefined behavior.

2023-02-21 20:40 UTC, pacu commented on Example/ZcashLightClientSample/ZcashLightClientSample/ViewController.swift
> +            state. And it may not be able to handle this state. It's suggested to remove the app and install it again. Sorry.
I think the main problem is dataDb and pendingDb. 

The other two we delete them anyway on start. Seeing it that way I'd say that it's acceptable because pendingDb will soon be part of DataDb and it won't be a problem. I'd tone down the wording though.

2023-02-22 09:36 UTC, Chlup commented on Example/ZcashLightClientSample/ZcashLightClientSample/ViewController.swift
> +            state. And it may not be able to handle this state. It's suggested to remove the app and install it again. Sorry.
I changed the documentation.

2023-02-22 11:50 UTC, pacu approved these changes

2023-02-23 08:38 UTC, merged