[#826] Change how the SDK is initialised
zcash/ZcashLightClientKit pull request #827
Opened 2023-03-10 12:10 UTC by Chlup

Closes #826

- `viewingKeys` and `walletBirthday` are removed from `Initializer` constuctor. These parameters are moved to `SDKSynchronizer.prepare` function.
- Any value emited from `lastState` stream before `SDKSynchronizer.prepare` is called has `latestScannedHeight` set to 0.
- `Initializer.initialize` function isn't public anymore. To initialize SDK call `SDKSynchronizer.prepare` instead.
- Real birthday is now known after the `SDKSynchronizer.prepare` is called. But this function isn't async and therefore it's hard to pass birthday from here to `CompactBlockProcessor` in synchronous manner. For this reason I created `Birthday` class which wraps birthday height. And only one instance of this class is used. So when `Initializer` stores computed birthday in this instance it's available in `CompactBlockProcessor`. It's not the cleanest way how to do this but for now it's probably simplest and fastest way how to do this.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-03-10 16:15 UTC, pacu requested changes
Great job!

Small request lets make `Birthday` more meaningful with some validation of the range.

2023-03-10 21:15 UTC, Chlup commented on Sources/ZcashLightClientKit/Model/Birthday.swift
> +public class Birthday {
I probably didn't want to go to this place with this type. In reality I just need class wrapper for the Int value. And because I am using it for wallet birthday I called it `Birthday`. It also invalid values from birthday perspective. When `Initializer` is created birthday is set to 0 before `initialize()` is called. Maybe it would be better to take one step back and don't use `Birthday` name for this.

2023-03-13 11:32 UTC, pacu requested changes
I'm not getting the sense of some of the changes, probably due to the lack of some context. 

I don't think I might be getting the problem so I can't say it's the right approach or not

2023-03-13 11:32 UTC, pacu commented on CHANGELOG.md
> +<<<<<<< HEAD
I think this swizzled in

2023-03-13 11:32 UTC, pacu commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +            walletBirthday: ReferenceContainer<BlockHeight>,
I don't understand how this change. 

Why is this reference container needed?

2023-03-13 11:32 UTC, pacu commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        let birthday: ReferenceContainer<BlockHeight>
Why do we need these two attributes that seem very similar in purpose?

2023-03-13 11:35 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        let birthday: ReferenceContainer<BlockHeight>
I tried to explain it in PR description:

Real birthday is now known after the `SDKSynchronizer.prepare` is called. But this function isn't async and therefore it's hard to pass birthday from here to `CompactBlockProcessor` in synchronous manner. We must be sure that it's safe to call `start()` after `prepare` function finishes. For this reason I created `ReferenceContainer` class which wraps birthday height. And only one instance of this class is used. So when `Initializer` stores computed birthday in this instance it's available in `CompactBlockProcessor`. It's not the cleanest way how to do this but for now it's probably simplest and fastest way how to do this.

2023-03-13 12:35 UTC, Chlup commented on Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
> +        let birthday: ReferenceContainer<BlockHeight>
ReferenceContrainer is gone. I changed the initial implementation to:

`CompactBlockProcessor` has `walletBirthdayProvider` instead of `walletBirthday`. And this new parameter is closure which reads birthday from `Initiliazer` on each call. Thanks to this `CompactBlockProcessor` has always the right birthday.

2023-03-13 14:20 UTC, pacu requested changes

2023-03-13 14:20 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +    private(set) public var walletBirthday: BlockHeight = .zero
If you already know what the network is, our "conceptual Zero" value is sapling activation height. Our SDK won't deal with any shielded funds from sprout.

2023-03-13 14:20 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +    func initialize(with seed: [UInt8]?, viewingKeys: [UnifiedFullViewingKey], walletBirthday: BlockHeight) throws -> InitializationResult {
this makes me think that there should be a different initializer. providing viewing keys and seed at the same time does not make sense for us, since we are not currently supporting spend capabilities and view-only keys from different seeds. 

if a user provides viewing keys that originate from other bytes than the seed bytes provided, the behaviour will be undefined

2023-03-13 14:20 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    public func prepare(
same comment as for `initialize` method

2023-03-13 14:20 UTC, pacu commented
Reviewed and notice there are a few more changes to do in regards to initialization

2023-03-13 14:32 UTC, Chlup commented on Sources/ZcashLightClientKit/Initializer.swift
> +    private(set) public var walletBirthday: BlockHeight = .zero
This value won't ever be used. Until `prepare()` is called (and this value is filled with real birthday) the `SDKSynchronizer` will be in `unprepared` state and refused to do anything. But to make this better I replace `.zero` with: 
`Checkpoint.birthday(with: 0, network: network).height`. 

Is that ok?

2023-03-13 14:42 UTC, pacu commented on Sources/ZcashLightClientKit/Initializer.swift
> +    private(set) public var walletBirthday: BlockHeight = .zero
Yes that will make it default to sapling activation

2023-03-14 07:54 UTC, Chlup commented on Sources/ZcashLightClientKit/Initializer.swift
> +    func initialize(with seed: [UInt8]?, viewingKeys: [UnifiedFullViewingKey], walletBirthday: BlockHeight) throws -> InitializationResult {
My change just moves `viewingKeys` and `walletBirthday` params from constructor to this method. I didn't created any new flows, logic or scenarios. Nothing prevented you before to pass viewing keys into constructor and then different seed into this function or to `prepare`.

2023-03-14 10:55 UTC, pacu approved these changes

2023-03-14 11:03 UTC, LukasKorba approved these changes

2023-03-14 11:30 UTC, merged