[#908] Add last and latest blocks data to Synchronizer State
zcash/ZcashLightClientKit pull request #911
Opened 2023-04-06 07:49 UTC by LukasKorba

Closes #908 

- added latest scanned time and latest block height
- fixed unit tests
- sample app showing the new values alongside with the %

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-04-06 12:32 UTC, Chlup requested changes

2023-04-06 12:32 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        if let latestBlockHeight = try? await blockProcessor.service.latestBlockHeight(), latestNetworkHeight < latestBlockHeight {
I talked with @LukasKorba  about this if we can afford to make API call every time snapshot of `SynchronizerState` is recreated. And @LukasKorba mentioned that we have timer in the SDK which ticks each 15 - 30 seconds and starts sync process and therefore make this API call. So after discussion we decided to put this API here.

I was thinking about it more. I think it shouldn't be here. In case that syncing is faster than this API call there will be delay between sync process and updates of state. I think we should create some "service" which calls this API call every 15 - 30 seconds. And `snapshotState(status:)`  function will take `latestBlockHeight` from this new "service". By this we won't introduce delay when updating status and reported `latestBlockHeight` should be reasonably actual. I think that we talked about this approach also with @LukasKorba but decided not to go in this way. After more thinking I think we should go this way.

2023-04-07 12:38 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        if let latestBlockHeight = try? await blockProcessor.service.latestBlockHeight(), latestNetworkHeight < latestBlockHeight {
i'm trying to wrap my head around how we should tackle this and if it's a priority for us.

2023-04-07 12:43 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        if let latestBlockHeight = try? await blockProcessor.service.latestBlockHeight(), latestNetworkHeight < latestBlockHeight {
My quick guess is that we could create a service that can try to get the latest block info every (1...AVG_BLOCK_TIME).randomInt() seconds. We have to note that fetching info within fixed intervals must be discouraged to avoid letting eavesdroppers anchor to these events to perform timing attacks on users.

2023-04-07 12:44 UTC, pacu requested changes
See comments above. Let's avoid requesting the latest block that much. either omit it entirely or solve it another way

2023-04-07 16:56 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        if let latestBlockHeight = try? await blockProcessor.service.latestBlockHeight(), latestNetworkHeight < latestBlockHeight {
That is exactly what I suggested in my comment.

2023-04-12 12:58 UTC, pacu requested changes
I left some architectural comments and some questions

2023-04-12 12:58 UTC, pacu commented on Sources/ZcashLightClientKit/Providers/LatestBlocksDataProvider.swift
> +    func updateScannedData() async {
I think this poses a problem because the data flows like this:

```
App <---- Synchronizer <---- CompactBlockProcessor 
```
Querying the transaction repository while scanning or creating a transaction can cause `database locked` error.
Also, the latest scanned height is always known by the compact block processor and updated by it. So the information of scanned blocks must bubble up from the actor actually controlling when scanning occurs rather than the client querying it.

2023-04-12 12:58 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    public var latestScannedTime: TimeInterval
Specify the anchor point of the time interval so the caller can know the reference from which it takes its value.


> A TimeInterval value is always specified in seconds; it yields sub-millisecond precision over a range of 10,000 years.
> On its own, a time interval does not specify a unique point in time, or even a span between specific times. Combining a time interval with one or more known reference points yields a [Date](doc://com.apple.documentation/documentation/foundation/date?language=swift) or [DateInterval](doc://com.apple.documentation/documentation/foundation/dateinterval?language=swift) value.
>

2023-04-12 12:58 UTC, pacu commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> -                newState = await snapshotState(status: newStatus)
@michal can you verify this refactor is not leaving out any logic that originated it?

2023-04-12 13:11 UTC, Chlup requested changes

2023-04-12 13:11 UTC, Chlup commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> -                newState = await snapshotState(status: newStatus)
Yes. We are good. This change actually also fixes #904.

2023-04-13 13:26 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    public var latestScannedTime: TimeInterval
Added comment that explains the anchor point.

2023-04-13 17:41 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Providers/LatestBlocksDataProvider.swift
> +    func updateScannedData() async {
Updated. 

I actually created a brand new latestScannedBlock API so I can read both timestamp and height in one go. The scanner was calling latestScannedHeight() and I changed it to latestScannedBlock() instead. That spot is safe and provider of height and timestamp is updated directly.  The
```
func updateScannedData() async
```
stayed for specific use cases but I added a comment and explained when to use it.

2023-04-13 19:27 UTC, pacu approved these changes

2023-04-14 07:08 UTC, merged