[#888] Add changelog and fix the documentation in ZcashRustBackendWelding
zcash/ZcashLightClientKit pull request #913
Opened 2023-04-06 13:55 UTC by Chlup

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-04-06 19:13 UTC, pacu requested changes

2023-04-06 19:28 UTC, Chlup commented on CHANGELOG.md
> +the `Initializer` and then call `Initializer.makeDerivationTool()` method.
Well. `DerivationTool` needs instance of the `ZcashRustBackendWelding`. And that is not public type. So `DerivationTool` now doesn't have public constructor. I mentioned this in description of the first PR - #898.

Do you have any suggestion how to solve this?

2023-04-06 19:32 UTC, pacu commented on CHANGELOG.md
> +the `Initializer` and then call `Initializer.makeDerivationTool()` method.
I haven't look at the code, but I wonder if we could extract the derivation functions from rustbackend to another piece that can only be instantiated with the ZcashNetwork id, which I believe is the only parameter you need to derive stuff for the right network

2023-04-06 19:35 UTC, Chlup commented on CHANGELOG.md
> +the `Initializer` and then call `Initializer.makeDerivationTool()` method.
Ok. Ok. I can check this out tomorrow. I will check which methods are used by DerivationTool and see if those can be extracted to another type. This is actually good idea. Thanks.

2023-04-07 16:54 UTC, Chlup commented on CHANGELOG.md
> +the `Initializer` and then call `Initializer.makeDerivationTool()` method.
It looks like that this is big issue. I tried different approaches and with each sooner or later I did hit a wall.

I tried what you suggested. `DerivationTool` is using mostly static methods from rust backend. But it also uses `deriveUnifiedFullViewingKey()` and `deriveUnifiedSpendingKey()` methods. These two are using `lastError()` therefore those must be async inside some actor. And when I divide `ZcashRustBackend` to two objects then there are two actors which aren't synchronised against each other. And race condition may happen.

So I left this and tried approach when the client app pass all the URLs and network to the `DerivationTool` constructor. It is little inconvenience but it should work. But then I realised that `DerivationTool` can't create another instance of the `ZcashRustBackend` because of thread safety. There can be only one instance of the `ZcashRustBackend` in the SDK.

Then I was thinking about making `rustBackend` available via `Initializer` so the client then can make `DerivationTool` with rust backend in constructor. But that is almost the same as if `Initializer` makes `DerivationTool`. And it would require to make `ZcashRustBackendWelding` public. Which is not desired. I tried few other approaches and nothing worked. 

I was thinking about making `DerivationTool` internal and move it's API to `Synchronizer`. We would also have to move making of the address objects to `Synchronizer`. Create some factory methods for address objects there. But this is big architectonical change.

Any idea?

2023-04-11 12:16 UTC, pacu approved these changes

2023-04-11 12:35 UTC, merged