[#361] Introduce ZcashError
zcash/ZcashLightClientKit pull request #917
Opened 2023-04-10 11:29 UTC by Chlup

This PR introduces `ZcashError` enum. This enum represents any error that can be thrown inside of the SDK and outside of the SDK. Also `ZcashError` is used in `LightWalletGRPCService` and handled in `CompactBlockProcessor` as example.

Why enum? First I tried this with some structure which contained code, message and underlyingError. Problem was when some specific place in the SDK would like to attach some additional data to error. I didn't want to add some generic dictionary to store anything with the error.

So I used enum to identify error. Each member can have specified amount of associated values. So specific error can bring some context data. And it's type safe.

Each error has also a code. Relationship between errors and codes is 1:1. It may looks bit redundant but it's important. The client app now can choose how to process errors. Either identify those by the error itself or by code.

Definition or errors and codes is in `ZcashErrorDefinition`. And then `ZcashError` and `ZcashErrorCode` are generated by Sourcery. Thanks to this it is easier to maintain the final code. And it gives us ability to generate any kind of documentation for the errors and codes. I created simple example of this in this PR. And it doesn't make the SDK completely dependent on the Sourcery. Final structures aren't super complicated and can be written manually if needed.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-04-11 10:13 UTC, pacu commented
adding @ccjernigan to align with Android SDK as well

2023-04-11 11:54 UTC, pacu requested changes
Great work. left minor comments suggesting changes

2023-04-11 11:54 UTC, pacu commented on Sources/ZcashLightClientKit/Error/Sourcery/ZcashErrorCodeHTMLDoc.stencil
I'd remove this and try to focus on generating docs with swiftdocs only

2023-04-11 11:54 UTC, pacu commented on Sources/ZcashLightClientKit/Error/Sourcery/generateHTMLFromErrorCodes.sh
Same as above. I'd remove this and focus on swiftdocs only.

2023-04-11 12:15 UTC, Chlup commented on Sources/ZcashLightClientKit/Error/ZcashError.swift
> +    /// Some testing code for now. Will be removed later.
This is fine. I want to keep it here for now to test all the generating and usage features. This PR is merged to feature branch. This will be removed later.

2023-04-11 12:16 UTC, Chlup commented on Sources/ZcashLightClientKit/Error/Sourcery/ZcashErrorCodeHTMLDoc.stencil
Removed.

2023-04-11 12:16 UTC, Chlup commented on Sources/ZcashLightClientKit/Error/Sourcery/generateHTMLFromErrorCodes.sh
Removed.

2023-04-11 12:33 UTC, pacu approved these changes

2023-04-12 12:07 UTC, LukasKorba approved these changes

2023-04-12 12:09 UTC, merged