[#950] Update error handling in rust backend
zcash/ZcashLightClientKit pull request #961
Opened 2023-04-13 12:20 UTC by Chlup

Closes #949
Closes #950

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-04-13 14:59 UTC, pacu requested changes
Great work. I left some suggestions. Some of them originate prior to this changes but it would be good to address them here

2023-04-13 14:59 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
>              zcashlc_clear_last_error()
I think this will be cleared on the `defer {}` block

2023-04-13 14:59 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            let error = UnsafeMutablePointer<Int8>.allocate(capacity: Int(errorLen))
I no realized that this is actually leaking the error because we are not deallocating this byte buffer

2023-04-13 14:59 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            if let errorMessage = String(validatingUTF8: error) {
Also this copies the pointed data so it's safe to deallocate afterwards

````Swift
/// Creates a new string by copying and validating the null-terminated UTF-8
    /// data referenced by the given pointer.
    ///
    /// This initializer does not try to repair ill-formed UTF-8 code unit
    /// sequences. If any are found, the result of the initializer is `nil`.
    ///
    /// The following example calls this initializer with pointers to the
    /// contents of two different `CChar` arrays---the first with well-formed
    /// UTF-8 code unit sequences and the second with an ill-formed sequence at
    /// the end.
    ///
    ///     let validUTF8: [CChar] = [67, 97, 102, -61, -87, 0]
    ///     validUTF8.withUnsafeBufferPointer { ptr in
    ///         let s = String(validatingUTF8: ptr.baseAddress!)
    ///         print(s)
    ///     }
    ///     // Prints "Optional("Café")"
    ///
    ///     let invalidUTF8: [CChar] = [67, 97, 102, -61, 0]
    ///     invalidUTF8.withUnsafeBufferPointer { ptr in
    ///         let s = String(validatingUTF8: ptr.baseAddress!)
    ///         print(s)
    ///     }
    ///     // Prints "nil"
    ///
    /// - Parameter cString: A pointer to a null-terminated UTF-8 code sequence.
    public init?(validatingUTF8 cString: UnsafePointer<CChar>)
````

2023-04-14 15:46 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - `rustGetNextAvailableAddressInvalidAddress` if generated unified address isn't valid.
Does this read in Xcode quick help? Because to my knowledge that's what SwiftDoc will support. If it does then that's ok.

2023-04-14 18:10 UTC, Chlup commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - `rustGetNextAvailableAddressInvalidAddress` if generated unified address isn't valid.
Xcode quick help doesn't render multiline throws. But I still think that documentation is more important than Xcode quick help. But if you think otherwise let's change it. How to do it? Put all the exceptions to one line? Or not to write `Throws` in the doc at all?

2023-04-14 18:38 UTC, Chlup commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - `rustGetNextAvailableAddressInvalidAddress` if generated unified address isn't valid.
I checked the SDK and this format of documentation is on multiple places. So I suggest not to block this PR with it. Because this PR blocks another PRs... And let's solve this in the whole SDK in #957.

2023-04-14 20:35 UTC, pacu commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    /// - `rustGetNextAvailableAddressInvalidAddress` if generated unified address isn't valid.
Agree

2023-04-14 20:37 UTC, pacu approved these changes

2023-04-17 05:49 UTC, merged